### ISSUE TITLE
Schakelschema 3D

### ISSUE THREAD

**Issue by AnneliesVlaar** [NatuurkundePracticumAmsterdam/ecpc#1]
Schakelschema 3D in handleiding zetten

**Comment by OlivierSwaak** [comment]
Het lukt me helaas niet om de blender files te openen. Elke keer wanneer ik het probeer, crasht het programma. 
We kijken morgen wel of we dit kunnen oplossen, als het niet lukt, zal ik mezelf van de issue af halen :).
Nu kan ik wel alvast uitzoeken hoe we .glb bestanden kunnen verwerken in de handleiding, dus daar ga ik nu mee bezig.

**Comment by OlivierSwaak** [comment]
Het is gelukt om m.b.v. modelviewer (https://modelviewer.dev/) een 3d model in de handleiding te verwerken. Ik ga nu nog kijken of ik de standaard camera-angle kan aanpassen.
https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/e730f6a1-c54d-4f23-9153-f962d39c5128

**Comment by OlivierSwaak** [comment]
De standaard camera-angle laat nu iets beter de schakeling zien.

![Image](https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/663cca11-b5e3-42db-bcdf-e430bb1f22cc)

**Comment by OlivierSwaak** [comment]
Met het attribuut 'autoplay' hoort het mogelijk te zijn om ook de animatie af te spelen, maar het is me nog niet gelukt om dit werkend te krijgen. Of misschien weet ik niet wat de animatie precies is :).
https://modelviewer.dev/examples/animation/#autoplay

**Comment by AnneliesVlaar** [comment]
How to use emmisive materials: https://www.reddit.com/r/threejs/comments/13gp30o/how_to_export_a_model_with_emission_for_the/

**Comment by OlivierSwaak** [comment]
> createAndApplyTexture('emissiveTexture', event);
https://modelviewer.dev/examples/scenegraph/
![image](https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/43ad3f9e-c5f4-46dd-9364-35b844350922)

**Comment by OlivierSwaak** [comment]
Het is me uiteindelijk wel gelukt om een animatie er in te krijgen alleen hij werkt niet zoals verwacht.

https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/3c5ae048-cde6-4167-84ea-10b9b55e9e47

Ik heb in plaats van de shader te animeren, heb ik een kopie gemaakt van het ledje.
Een daarvan straalt licht uit, de andere niet.
Het moment dat hij aangaat, gaat de scale van het ledje dat geen licht uitstraalt naar 0% en als hij uitgaat komt dat ledje weer tevoorschijn en gaat de scale van het ledje dat wel licht uitstraalt naar 0%.
Ik heb de blender file onder assets/circuit gezet op de branch.

**Comment by AnneliesVlaar** [comment]
Het ziet er niet heel spectaculair uit met het knipperende lichtje, ik ga even kijken wat we eraan kunnen doen.
