### ISSUE TITLE
Standaard structuur voor opdrachten

### ISSUE THREAD

**Issue by OlivierSwaak** [NatuurkundePracticumAmsterdam/ecpc#13]
Maak een standaard structuur van hoe de opdrachten zijn opgebouwd.
Denk aan user stories, pseudo code, input/output geven.
Eindig (elke) opdracht met een exit kaart.

**Comment by AnneliesVlaar** [comment]
Exit tickets zijn meer bedoeld om kort feedback te vragen van studenten of om ze zelf een take home message te laten maken. Wij zijn denk ik meer opzoek naar een soort controleer-kaart.

**Comment by AnneliesVlaar** [comment]
Ik heb de opdracht Quick 'n dirty meeting opgeknipt in drie delen, met behulp van tabjes

Dit was de originele opdracht:
![image](https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/66774020/9b1a317d-d126-421e-ab6f-279c6e4e956f)


In het eerste tabje een beschrijving van de opdracht.
![image](https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/66774020/5f6156a4-4157-4fcc-a922-63f00825d401)


In het tweede tabje een minimalistische opzet van de code:
![image](https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/66774020/16d1960e-d54b-4f59-bedb-2409a916dd07)

In het derde tabje een checklist (clickable maar wordt niet opgeslagen)
![image](https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/66774020/d203d75e-2413-4314-8777-7205e7f5dd8b)

**Comment by AnneliesVlaar** [comment]
Om duidelijk te maken welke opdrachten bij elkaar horen en welke opdrachten nog zullen volgen, een paragraaf 'Projecttraject' toegevoegd:

![image](https://github.com/user-attachments/assets/8e23a4ed-d4bf-45b2-aae0-eb9108ca6696)

**Comment by AnneliesVlaar** [comment]
De testcode hoort eigenlijk bij het check-tabblad

![image](https://github.com/user-attachments/assets/38571bb4-8735-4af0-affb-01890fb826a0)

Maar misschien is het beter om een code-tabblad te maken:
![image](https://github.com/user-attachments/assets/8583a8d8-b30a-4b6a-b500-d00091478080)

Dan ziet het check-tabblad er weer wat vriendelijker uit:
![image](https://github.com/user-attachments/assets/cfb9e224-2869-4757-bce1-2d2ef2239f9c)

**Comment by AnneliesVlaar** [comment]
Opdrachten om uit te testen hoe die in een standaardstructuur passen:

* Command-line interface
   * Argumenten toevoegen
   * Test hello
   * Pauze optie
   * Argumenten en opties
   * Smallangle
   * Alle opdrachten onder: Command-line interface voor ons experiment

**Comment by OlivierSwaak** [comment]
> De testcode hoort eigenlijk bij het check-tabblad
> 
> ![image](https://private-user-images.githubusercontent.com/66774020/355067881-38571bb4-8735-4af0-affb-01890fb826a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NjA0OTcsIm5iZiI6MTcyMjg2MDE5NywicGF0aCI6Ii82Njc3NDAyMC8zNTUwNjc4ODEtMzg1NzFiYjQtODczNS00YWYwLWFmZmItMDE4OTBmYjgyNmEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDEyMTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNDQ1ODMzMDFmZTljMTQzM2JhMDIwZjUzYjBjNzFlYzA4ODcwYTY5ZTZlZGZhZDE4MzEyOTQwZGU0MTc4NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lF0PwtxqSELx8MCDDXKDcTcR1CiIWh7oYRm_uugaDg0)
> 
> Maar misschien is het beter om een code-tabblad te maken: ![image](https://private-user-images.githubusercontent.com/66774020/355068020-8583a8d8-b30a-4b6a-b500-d00091478080.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NjA0OTcsIm5iZiI6MTcyMjg2MDE5NywicGF0aCI6Ii82Njc3NDAyMC8zNTUwNjgwMjAtODU4M2E4ZDgtYjMwYS00YjZhLWI1MDAtZDAwMDkxNDc4MDgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDEyMTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlMzc2OTk5MWZiNTkzZjE3YTI3ZGVkNDMzZTBjY2YwN2RjZmFlZDQyZGRkMzBhMzdkZTQ2ZmUyMjEyNTE4ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2bWSkOYBfVIqYH8c7uFoSYzZBs42eNaOMAGyMmtPbN0)
> 
> Dan ziet het check-tabblad er weer wat vriendelijker uit: ![image](https://private-user-images.githubusercontent.com/66774020/355068124-cfb9e224-2869-4757-bce1-2d2ef2239f9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NjA0OTcsIm5iZiI6MTcyMjg2MDE5NywicGF0aCI6Ii82Njc3NDAyMC8zNTUwNjgxMjQtY2ZiOWUyMjQtMjg2OS00NzU3LWJjZTEtMmQyZWYyMjM5ZjljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDEyMTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlYjBiMGRjMWI1NzZlMGZjYzQ2MWEyMGM3NTc2MTQxYWM1ZGMxZjViY2E1YmM2MWRmY2E3YWY4MmU4YTM5ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xLnR64Bo6QIho_spCnaz-7fXVW0Vc0XBP9-XgbZplO8)

Ja ik denk dat een code tabblad met een apart tabblad voor de checklist een goed idee is

**Comment by OlivierSwaak** [comment]
# Command-line interface
[ ] Argumenten toevoegen
[ ] Test hello
[ ] Pauze optie
[ ] Argumenten en opties
[ ] Smallangle

[ ] Pythondaq: commando's
[ ] Pythondaq: `scan`
[ ] Pythondaq: herhaalmetingen
[ ] Pythondaq: `list`
[ ] Pythondaq: choose device
[ ] Pythondaq: `info`
[ ] Pythondaq: Helpteksten
[ ] Pythondaq: Grafiek

**Comment by OlivierSwaak** [comment]
Argumenten en opties was nog lastig om te verwerken in deze nieuwe stijl.

![Image](https://github.com/user-attachments/assets/f26d4dd3-3a2c-4aa3-935e-e964311db072)

Normaal willen we eigenlijk dat deze stappen onder de checklist staan, alleen sommige stappen moeten gedaan worden voordat ze beginnen met programmeren (test of alles nog doet), dus voor nu laat ik het als deze bulletpoints staan

**Comment by AnneliesVlaar** [comment]
> Argumenten en opties was nog lastig om te verwerken in deze nieuwe stijl.
> 
> ![Image](https://private-user-images.githubusercontent.com/90635681/355430733-f26d4dd3-3a2c-4aa3-935e-e964311db072.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NDUwNTgsIm5iZiI6MTcyMjk0NDc1OCwicGF0aCI6Ii85MDYzNTY4MS8zNTU0MzA3MzMtZjI2ZDRkZDMtM2EyYy00YWEzLTkzNWUtZTk2NDMxMWRiMDcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDExNDU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyOGFiOTVhYmM1YWMzNGUwMDc5MDU3NmIxN2ExMDNiOWQyMDUyM2RmYzk5MzQ1YWE2OTU0OWZkOTk3OTFmNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8sIaFBJBKFB1Sy--L8Qrg-N-ET7zVXVuWt4Z4AahN0o)
> 
> Normaal willen we eigenlijk dat deze stappen onder de checklist staan, alleen sommige stappen moeten gedaan worden voordat ze beginnen met programmeren (test of alles nog doet). Ik ben bang dat als dit pas bij de checklist staat, dat ze beginnen met programmeren wanneer ze bij het kopje 'code' zijn en het missen, dus voor nu laat ik het als deze bulletpoints staan

Ik denk dat we dit wel kunnen herschrijven naar een user story... Je test de applicatie door een nieuwe environment aan te maken en de applicatie te installeren. 

Eventueel kan het een nieuwe opdracht worden opdracht 'test' en opdracht 'argumenten en opties'

**Comment by OlivierSwaak** [comment]
![Image](https://github.com/user-attachments/assets/505c5932-e791-42c9-a151-ccbd4873debf)

3. als een terminal onder code
4. user story

**Comment by AnneliesVlaar** [comment]
Hoofdstukken waarin de basis/inlever-opdrachten zijn omgeschreven naar standaard structuur

- [ ] Communicatie
- [ ] Github
- [ ] Basisscript
- [ ] Classes
- [ ] MVC
- [ ] Docstrings
- [ ] Poetry
- [ ] CLI
- [ ] GUI

**Comment by OlivierSwaak** [comment]
Bij sommige opdrachten spreekt het 'code' tabblad nog niet helemaal voor zich
![Image](https://github.com/user-attachments/assets/2bc6323d-07bd-4e14-b8ad-10fe1160f380)

**Comment by OlivierSwaak** [comment]
![Image](https://github.com/user-attachments/assets/76b45fdb-884d-42cd-a893-eafd1f34fe8d)

Hier nemen we ook een klein beetje 'vrijheid' weg met hoe de studenten deze lijst weergeven. Volgens mij is het standaard een tuple (?), dus dan gaan ze het omzetten naar een lijst, wat niet per se verkeerd is, maar je hebt misschien ook studenten die het wat leuker aankleden en de entries onder elkaar printen. Alleen zeggen we nu tegen deze studenten, stop met die creativiteit, output het op deze manier.

**Comment by OlivierSwaak** [comment]
![image](https://github.com/user-attachments/assets/2a7cb49c-32b8-4aaa-adea-9eb0012aba4a)
Het toevoegen van de code hier zorgt voor wat problemen en maakt de website op de een of andere manier een stuk trager, ik zal er later naar kijken waardoor het komt.

**Comment by AnneliesVlaar** [comment]
> ![Image](https://private-user-images.githubusercontent.com/90635681/364019884-76b45fdb-884d-42cd-a893-eafd1f34fe8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDEwNDAsIm5iZiI6MTcyNTQ0MDc0MCwicGF0aCI6Ii85MDYzNTY4MS8zNjQwMTk4ODQtNzZiNDVmZGItODg0ZC00MmNkLWE4OTMtZWFmZDFmMzRmZThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA5MDU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhOTU4MTkwMTQwMDQ5Yjk2Y2YyNWNhMDE4ZTRhZDg0YTA3YzEzYzAzMDNhMDdhMDk5M2IzOWNlYjdmNjM4NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2NplyCzLhJ2KzTmW23e2gdJHhOWgIa2jNH9b7jFWgZQ) (de output is voor nu nog een placeholder)
> 
> Hier nemen we ook een klein beetje 'vrijheid' weg met hoe de studenten deze lijst weergeven. Volgens mij is het standaard een tuple (?), dus dan gaan ze het omzetten naar een lijst, wat niet per se verkeerd is, maar je hebt misschien ook studenten die het wat leuker aankleden en de entries onder elkaar printen. Alleen zeggen we nu tegen deze studenten, stop met die creativiteit, output het op deze manier.

Helpt het als we het met minder syntax neerzetten: ```# lijst met devices```?
