### ISSUE TITLE
ADC sliders

### ISSUE THREAD

**Issue by AnneliesVlaar** [NatuurkundePracticumAmsterdam/ecpc#14]
Met sliders laten zien wat het verschil is tussen continu en discrete stappen met betrekken tot ADC en voltage.

**Comment by OlivierSwaak** [comment]
Wat is er al?

**Comment by OlivierSwaak** [comment]
Twee horizontale sliders: de continue boven en een discrete onder
De max van de discrete slider kan worden ingesteld m.b.v. een textbox

https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/53573b6f-f269-47fa-8ab2-f0071ff75b8a

**Comment by OlivierSwaak** [comment]
Gebruik van de default slider met ticks kan vervelend zijn: https://stackoverflow.com/questions/26612700/ticks-for-type-range-html-input
Verticaal oriënteren van slider: https://stackoverflow.com/questions/15935837/how-to-display-a-range-input-slider-vertically

**Comment by OlivierSwaak** [comment]
Eventueel met border:
![image](https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/19df0d23-6584-4374-8e08-2c752f33f58b)

**Comment by OlivierSwaak** [comment]
# Optie 2
Dropdown menu als max selector

https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/b293c237-d80c-429f-beb2-6976fcd9422f

Voordelen: makkelijker te besturen
Nadelen: Minder 'exploration'

**Comment by OlivierSwaak** [comment]
Ik zal morgen/overmorgen kijken of ik de slider verticaal kan krijgen.

**Comment by AnneliesVlaar** [comment]
> Ik zal morgen/overmorgen kijken of ik de slider verticaal kan krijgen.

Zo onder elkaar horizontaal is het ook al heel mooi vergelijkend. Dan past het mogelijk ook beter in de handleiding, anders krijgen we een groot leeg vlak ernaast?

**Comment by OlivierSwaak** [comment]
Ja lijkt mij ook, het zou dan eventueel naast deze foto kunnen
![image](https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/8db9c34d-4091-4e6d-ae98-301730582f44)
maar dat kan ook een beperking zijn op hoe groot de slider is, dus ik zal hem voor nu zo houden.
Ik wil nu nog kijken of ik de specifieke values ook kan laten zien bijvoorbeeld aan de hand van een label die uit de button popt, zoals de mockup hieronder:
![mockup_adcsliders](https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/6c011a9a-37b8-4129-923f-c01db13ca241)

**Comment by OlivierSwaak** [comment]
![image](https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/e21ebaac-8fcc-4bb0-94c3-0006ec379c44)
https://github.com/material-components/material-components-android/issues/1316
Iets in deze richting

**Comment by OlivierSwaak** [comment]
Eerst probeerde ik het aan de hand van het volgende stackoverflow antwoord: https://stackoverflow.com/a/35391072
https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/64fcb751-6782-4c7f-8a0b-b4331b3f3f1f
Maar de offset werd niet goed berekend waardoor het steeds verschoof.

Ik heb nu een andere oplossing gevonden die ik ga proberen te gebruiken:
https://css-tricks.com/value-bubbles-for-range-inputs/

**Comment by OlivierSwaak** [comment]
Met deze nieuwe methode is het me gelukt om labels toe te voegen

https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/d1d158c1-4134-4718-a7ae-1f3d3f333460

**Comment by OlivierSwaak** [comment]
Verder is er nog een bug met het reloaden van de website. De max range wordt gereset naar 15, maar de ingevulde waarde niet. Aangezien dit niet zo heel belangrijk is, zal ik er niet teveel tijd aan spenderen om dit te fixen.

https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/1e9f850e-fc82-4c09-9e68-e364049793ec

Er zijn hier twee mogenlijkheden: of we updaten de value van de textbox bij startup of de max range bij startup

**Comment by OlivierSwaak** [comment]
Verder moeten we ook alleen maar integer values accepten bij zo'n textbox

**Comment by OlivierSwaak** [comment]
> Verder is er nog een bug met het reloaden van de website. De max range wordt gereset naar 15, maar de ingevulde waarde niet. Aangezien dit niet zo heel belangrijk is, zal ik er niet teveel tijd aan spenderen om dit te fixen.
> slider_reload.mp4
> 
> Er zijn hier twee mogenlijkheden: of we updaten de value van de textbox bij startup of de max range bij startup

https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/4bd9fea9-0449-4faa-a85d-266726078e98

Het is gelukt, hij update nu de max van de range at startup.

**Comment by OlivierSwaak** [comment]
> Verder moeten we ook alleen maar integer values accepten bij zo'n textbox

Lijkt vrij moeilijk te zijn, ik kreeg het niet snel werkend, dus we moeten kijken hoe belangrijk we dit vinden om verder uit te zoeken.

https://stackoverflow.com/questions/469357/html-text-input-allow-only-numeric-input
https://javascript.plainenglish.io/how-to-make-an-input-only-accept-integers-9cc54f6217ad
https://sentry.io/answers/html-text-input-allow-only-numeric-input/

**Comment by OlivierSwaak** [comment]
Dropbox, 3 keuzes

**Comment by OlivierSwaak** [comment]
Samenvoegen slider en label

**Comment by OlivierSwaak** [comment]
Maak deelbaar element van met --8<-- html bestand

**Comment by OlivierSwaak** [comment]
Eventueel deel-knopje

**Comment by OlivierSwaak** [comment]
Kleuren aanpassen naar ECPC of naar mkdocs

**Comment by OlivierSwaak** [comment]
> Kleuren aanpassen naar ECPC of naar mkdocs

Donkere kleur voor slider handle te donker
![image](https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/e800b30d-383d-484b-84ac-519b504cf1a9)

Daarom lichte kleur voor handle en donkere kleur voor label
![image](https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/7ab7f191-c201-4b0b-b4ac-999c31d77602)

**Comment by OlivierSwaak** [comment]
Op verschillende monitoren is de label net op een ander plekje
![image](https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/9650fbf2-da96-4dc9-865a-be5ed76a9437)

**Comment by OlivierSwaak** [comment]
> Samenvoegen slider en label

Gelukt, ziet er overzichtelijk uit

https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/a00a9056-700f-480d-bedd-83c507808658

**Comment by OlivierSwaak** [comment]
Wederom met de ECPC kleuren:
![image](https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/5c17812c-9f0a-4df3-bd17-3db14401dbae)
De mkdocs versie ziet er beter uit, naar mijn mening.

**Comment by OlivierSwaak** [comment]
> Maak deelbaar element van met --8<-- html bestand

Het is me nog niet gelukt om daadwerkelijk een extern html bestand erin te 'snippeten'. 
Ik heb het wel samengevoegd in één html bestand (waar nog veel redundant code in staat)
![image](https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/cd490a02-f799-4fcb-8541-d527f098fab5)
maar de CSS is dus vrij website-specifiek, dus dat is niet helemaal 'plug-and-play', maar dit kan de gebruiker zelf aanpassen.

**Comment by OlivierSwaak** [comment]
Ik zal kijken of ik de labels automatisch kan laten centreren aangezien dit per monitor verschilt:
![image](https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/67347e8f-fffa-4037-81f1-876fb2de87af)
de grote monitor en
![image](https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/3a2b2054-0038-42d1-a1d2-1900b421370a)
de kleine, maar dit is een klein detail.

**Comment by AnneliesVlaar** [comment]
> > Samenvoegen slider en label
> 
> Gelukt, ziet er overzichtelijk uit
> 
>  2024-07-08.16-24-31.mp4

Het ziet er zeker overzichtelijk uit. Het lijkt wel alsof het moeilijker te zien is wat continu en discontinu doet omdat de labels van verschillende grote zijn. Bij de circel zag je heel duidlijk wanneer ze niet uitgelijnd waren.

**Comment by OlivierSwaak** [comment]
Labels naast tekst.

**Comment by OlivierSwaak** [comment]
Tekst selecteren uitzetten.

**Comment by OlivierSwaak** [comment]
3.3 V.

**Comment by OlivierSwaak** [comment]
" Ik zag dat ik die class.html als iframe erin gezet (https://github.com/NatuurkundePracticumAmsterdam/ecpc/commit/76e6077a79157e6ba48db63ba84bd1d9a76b2e66) dus misschien dat snippets idd niet werken. "

**Comment by OlivierSwaak** [comment]
> " Ik zag dat ik die class.html als iframe erin gezet ([76e6077](https://github.com/NatuurkundePracticumAmsterdam/ecpc/commit/76e6077a79157e6ba48db63ba84bd1d9a76b2e66)) dus misschien dat snippets idd niet werken. "

![image](https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/1d2aa885-227c-4736-9052-8e279b482162)
Het is me gelukt om de afgesplitste html als iframe in de handleiding te zetten. Ik heb het font van mkdocs, Roboto, er achteraf nog aan toe moeten voegen, maar het ziet er nog steeds niet helemaal hetzelfde uit. We kunnen hier altijd later nog naar kijken, maar de source code staat nu, met Roboto, in assets/ADC_slider, dus daar kan altijd alles gehaald worden.

**Comment by OlivierSwaak** [comment]
Ik heb de demo als een grijze opdracht toegevoegd. De tekst van de opdracht is niet definitief. Ik weet nog niet helemaal hoe ik opdrachten goed kan uitzetten.
![image](https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/49cd0690-f7f5-4864-9242-28649233737c)
