### ISSUE TITLE
Poetry is een moeilijk en langdurend hoofdstuk

### ISSUE THREAD

**Issue by OlivierSwaak** [NatuurkundePracticumAmsterdam/ecpc#17]
Het hoofdstuk poetry duurde vorig jaar te lang voor de studenten.
Maak poetry sneller m.b.v. bijvoorbeeld gifjes van de terminal en cheatsheets.

**Comment by OlivierSwaak** [comment]
https://github.com/NatuurkundePracticumAmsterdam/ecpc/issues/2#issuecomment-2214046210

**Comment by OlivierSwaak** [comment]
Terminal met output: bijv. rode tekst. Vergelijken wat je verwacht vs wat je krijgt.

**Comment by OlivierSwaak** [comment]
Run knop terminal, enter knop.

**Comment by OlivierSwaak** [comment]
![image](https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/a3d25a9f-b3e1-4034-9728-313b1eacc842)
Hier hoeft alleen knop + de bestandsnaam met de output.

**Comment by AnneliesVlaar** [comment]
Wat doet Poetry verduidelijken met analogie #35
Veranderingen in mappenstructuur aangeven met groen map/bestand icoontje #36
Navigeren in terminal speciek aanleren met nieuwe opdracht #33
