### ISSUE TITLE
class diagrams

### ISSUE THREAD

**Issue by AnneliesVlaar** [NatuurkundePracticumAmsterdam/ecpc#20]
Classes weergeven met diagrams, waarin attributes en methods zijn weergegeven.

**Comment by AnneliesVlaar** [comment]
@OlivierSwaak Kan jij een voorbeeld geven van hoe zo'n diagram eruit ziet?

**Comment by OlivierSwaak** [comment]
![Class-Diagram-example](https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/9d21529d-5f01-41ea-83c2-ca0e77684732)
Dit is al een vrij simpel voorbeeld van meerdere class diagrams die met elkaar praten. Volgens mij wordt hier een inheritance laten zien. 
Voor python zijn die plusjes en minnetjes niet echt nodig. We zouden eventueel erover na kunnen denken of het type van de attribuut belangrijk is.

![single_diagram](https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/35adc0c4-7e68-4abb-936e-bdf3f3ad5bed)

Of dus

![single_diagram_minimal](https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/dd3ec777-cdef-4559-8bda-28fee1256a5c)

**Comment by davidfokkema** [comment]
Omdat type hints in Python meer en meer gebruikt worden is het denk ik wel goed om ze er wél bij te zetten. We gaan (denk ik?) type hints nog niet voor alle studenten introduceren in de cursus (maar kan wel een mooie verdieping zijn) maar het is denk ik wel goed om aan te geven wat voor soort object je verwacht. Zo moet 'age' iets zijn als 65 en niet 'old', 'toddler', 'teenager', etc.

**Comment by davidfokkema** [comment]
Ik zou daar dan ook de Python-classes voor gebruiken, dus `gender: str` en niet `gender: String` bijvoorbeeld.

**Comment by AnneliesVlaar** [comment]
Zien voorlopig geen toegevoegde waarde
