### ISSUE TITLE
Visuele trigger voor aanmaken nieuwe environments/repositories/...

### ISSUE THREAD

**Issue by OlivierSwaak** [NatuurkundePracticumAmsterdam/ecpc#21]
Net zoals voor inleveropdrachten en paarse opdrachten, probeer een visuele trigger te maken voor elke keer als een nieuwe environment of repository aangemaakt moet worden met bijvoorbeeld een speciaal kleurtje.

**Comment by AnneliesVlaar** [comment]
hangt samen met #13 gaan we in de checklijst zetten dat ze een nieuwe environment of repository moeten aanmaken?

**Comment by AnneliesVlaar** [comment]
kan met een verwijzing naar de cheatsheet zie #54

**Comment by AnneliesVlaar** [comment]
lampje wordt visuele trigger die verwijst naar cheatsheet zie #54
