### ISSUE TITLE
Motivatie opsplitsen script in classes 

### ISSUE THREAD

**Issue by AnneliesVlaar** [NatuurkundePracticumAmsterdam/ecpc#22]

**Comment by OlivierSwaak** [comment]
Veel studenten hebben profijt gehad van het aparte class-hoofdstuk. Ik denk dat de motivatie nu vrij duidelijk is. Zeker de zin 'Het scheiden van je programma in deze lagen kan enorm helpen om ervoor te zorgen dat je geen spaghetticode schrijft — ongestructureerde en moeilijk te begrijpen code' is hier heel duidelijk in (maar die stond er waarschijnlijk al)!
