### ISSUE TITLE
Cheatsheets voor bijvoorbeeld poetry en conda

### ISSUE THREAD

**Issue by OlivierSwaak** [NatuurkundePracticumAmsterdam/ecpc#23]
Maak cheatsheets voor handelingen die vaak nodig zijn zoals poetry initialiseren of conda environment aanmaken.

**Comment by AnneliesVlaar** [comment]
Overzicht van cheatsheet van oud student:

Conda:
- nieuw environment
- package installeren

Github:
- bestaande map als repository toevoegen

Poetry:
- Poetry installeren
- nieuw Poetry project
- package installeren
- dependency toevoegen
-

**Comment by davidfokkema** [comment]
De handeling 'maak nieuw project' is ook lastig: eerst poetry new en dan GitHub? Of eerst GitHub en dan poetry new?

**Comment by OlivierSwaak** [comment]
Nadat poetry wordt geïntroduceerd maakt het natuurlijk uit of we een conda environment aanmaken voor een geheel nieuw project of dat we een environment aanmaken om te controleren of het poetry project wel goed ingesteld is.

**Comment by AnneliesVlaar** [comment]
navigatie naar cheatsheet in appendix of vanuit de header

**Comment by OlivierSwaak** [comment]
# Environment aanmaken
### Initieel

![Image](https://github.com/user-attachments/assets/11ccde7a-7a1d-4b81-b8f2-224080ab4178)

### Empty

```conda create -n pythondaq python=3.10```
Installeer je dependencies met pip/conda install

### Nadat je een poetry project hebt

```conda create -n pythondaq python=3.10
poetry install```

## Cheatsheet
Tab 1 voor poetry
1. Maak een nieuwe environment aan met ```conda create -n [naam] python=3.10```
2. Installeer je dependencies met pip/conda install (welke willen we liever gebruiken?)

Tab 2 na poetry
1. Maak een nieuwe environment aan met ```conda create -n [naam] python=3.10```
2. Installeer je dependencies met ```poetry install```

**Comment by OlivierSwaak** [comment]
# Github
1. Maak in de map ECPC een nieuwe map voor je repository aan
2. Open Github Desktop
3. File > Add repository en kies de aangemaakte map
4. Druk op de blauwe tekst <code>Create repository</code>
5. Vink <code>Initialize this repository with a README</code>
6. Kies bij <code>Git ignore</code> voor "Python"
7. Bevestig met de blauwe knop <code>Create Repository</code>

**Comment by OlivierSwaak** [comment]
# Poetry
### Compleet nieuw project
<code>poetry new --src [naam]</code>

### Installeren van je package
<code>poetry install</code>

### Toevoegen van dependencies
<code>poetry add [dependency]</code>

### Alleen <code>pyproject.toml</code>
<code>poetry init --no-interaction</code>

### Commandos toevoegen
Voeg onder <code>[tool.poetry.scripts]</code> een commando toe met:
<code>naam_commando = "package.module:naam_functie"</code>

## Cheatsheet
Tab 1 volledig nieuw project
1. Open de map ECPC met Visual Studio Code
2. Maak een nieuw project aan met <code>poetry new --src [naam]</code>
3. Open de projectmap (de map waar <code>pyproject.toml</code> in staat) met Visual Studio Code.
4. Installeer je poetry project met <code>poetry install</code>
5. Voeg je dependencies toe met <code>poetry add [dependency]</code>
6. Elke keer wanneer je een commando toevoegt of in een nieuwe conda environment zit, installeer je project opnieuw met <code>poetry install</code>

Tab 2 alleen <code>pyproject.toml</code>
1. Maak een nieuwe map voor je project aan in de map ECPC
2. Open de map met Visual Studio Code.
3. Maak een nieuw project aan met <code>poetry init --no-interaction</code>
4. Maak de volgende mappenstructuur aan: [boomstructuur met src, tests en de __init__.py]
6. Installeer je poetry project met <code>poetry install</code>
7. Voeg je dependencies toe met <code>poetry add [dependency]</code>
8. Elke keer wanneer je een commando toevoegt of in een nieuwe conda environment zit, installeer je project opnieuw met <code>poetry install</code>

**Comment by OlivierSwaak** [comment]
Mijn idee is om de hele tijd rechtsboven een lightbulb te hebben, als het nodig is kunnen we deze laten oplichten zodat de studenten weten waar ze moeten drukken. 
Simpelste is om met de lightbulb naar een andere pagina te verwijzen waar de cheatsheets staan. We willen echter het 'heen-en-weer klikken' verminderen, dus ik wil kijken of ik het iets van een pop-up kan maken, dat de cheatsheets 'uit' de header komen.

![image](https://github.com/user-attachments/assets/c7645b45-ab95-4c51-aefb-ffd193de7359)

**Comment by OlivierSwaak** [comment]
Ik heb nu animaties en een placeholder cheatsheet toegevoegd aan dit knopje.

https://github.com/user-attachments/assets/5cd00b34-d8b6-4ce6-8f85-c82bb4c6ef74

Ik wil dit uiteindelijk een soort embedded html pagina maken, zodat de cheatsheets onder elkaar kunnen staan en dat je kan scrollen tot waar je het nodig hebt. We zouden eventueel ook door te kijken naar op welke pagina je bent sommige dingen wel of niet laten zien (bij les 1 heb je nog geen poetry nodig).

Zoals je kan zien aan het einde van de video moeten we ook nog nadenken over hoe we de cheatsheet miss naar het midden van de pagina moeten verschuiven als er wordt ingezoomd om er zo voor te zorgen dat het niet de rechterkant van het venster clipt. Dit is zeker belangrijk als studenten bijvoorbeeld splitscreen gebruiken tijdens het schrijven van de code (splitscreen van VSCode en de handleiding), dat de cheatsheet leesbaar blijft.

**Comment by OlivierSwaak** [comment]
Om ervoor te zorgen dat hij in de midden van de pagina blijft heb ik de alignment en de breedte van het element aangepast.

https://github.com/user-attachments/assets/17628ec6-bc01-419a-bab2-326f2a6e8a14

Ik vond het mooier toen hij uit het midden van de lightbulb kwam, maar nu blijft hij wel met elke scaling mooi in het midden van de pagina (althans hij houdt de breedte van de header aan die tussen de titel van het kopje is en de search bar).

**Comment by OlivierSwaak** [comment]
Cheatsheets standaard ingeklapt

**Comment by OlivierSwaak** [comment]
Lightbulb icoon wit

**Comment by AnneliesVlaar** [comment]
Een cheatsheet met als eerste een aantal hoofdstukken GitHub, Poetry, Conda
![Cheatsheet-first-level](https://github.com/user-attachments/assets/c04e859c-7ec6-40ba-855c-6850c52a3cc0)

Door op het hoofdstuk te klikken kom je op een tweede pagina met paragrafen:
![Cheatsheet-second-level](https://github.com/user-attachments/assets/df18b6fb-e4f6-43fb-8f7f-18618119483c)

Daarna zie je dan de cheatsheet, met bovenin de navigatiebar waarmee je weer terug kan naar een vorig level, door te klikken op het hoofdstuk of de paragraaf (of het > tekentje):
![Cheatsheet-third-level](https://github.com/user-attachments/assets/3c5f5c12-8636-413a-9176-8a8de101c035)

**Comment by OlivierSwaak** [comment]
Het is me nu gelukt om de embedded pagina er wat breder te displayen en ik heb het icoontje wit gemaakt.

https://github.com/user-attachments/assets/b6751f58-d292-4534-bcb1-e1f4bf713c3b

Zoals verwacht krijgen we een recursieve cheatsheet, dus ik zal kijken of ik de header weg kan halen

**Comment by OlivierSwaak** [comment]
Het is me gelukt om de header weg te krijgen en door de verhoudingen van de embed, is de navigatie nergens te bekennen.

https://github.com/user-attachments/assets/1b1df5fa-1e30-4aa5-bf6a-99ec6425d03d

Door de manier waarop ik dit heb gedaan, mist de cheatsheets in de appendix wel een header, maar ik vind dat op dit moment niet belangrijk genoeg om op te lossen.

**Comment by OlivierSwaak** [comment]
Verder springt het beeld op en neer elke keer als we naar een nieuwe pagina gaat, omdat het heel even de header inlaadt en vervolgens weer weghaalt. Dit kan visueel een beetje irritant zijn, maar ik weet niet hoe we dit makkelijk kunnen oplossen, we zouden hier eventueel later nog naar kunnen kijken, maar het heeft geen prioriteit.
