### ISSUE TITLE
Syntax commands invuloefening

### ISSUE THREAD

**Issue by AnneliesVlaar** [NatuurkundePracticumAmsterdam/ecpc#25]
```
[tool.poetry.scripts]
naam_commando = "package.module:naam_functie"
```

**Comment by OlivierSwaak** [comment]
![image](https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/9cf547bd-e0f1-4d84-8270-0e1ce4ada5c0)
Bij punt 4 ipv het al te geven een invul/sleep oefening.

**Comment by AnneliesVlaar** [comment]
fill in the blanks:
![image](https://github.com/user-attachments/assets/1eb07000-9ce9-4fd4-aeae-732dcb2cddbf)
puntjes zijn bijna niet te zien. geen uitnodigende uiterlijk om iets in te gaan vullen.

**Comment by AnneliesVlaar** [comment]
@OlivierSwaak kan jij kijken of we dit via H5P zelf als code kunnen weergeven?

**Comment by OlivierSwaak** [comment]
Ik probeerde dit door gelijk de tekst van het h5p element te omringen met `<pre><code>`: 
![image](https://github.com/user-attachments/assets/111744ff-a7e1-4f3a-a658-1fe7ba4edb66)
maar dat werkte helaas niet
![image](https://github.com/user-attachments/assets/f5301ae9-e87a-4de1-a4cd-5b45fe53561d)

**Comment by OlivierSwaak** [comment]
We moeten buiten `<p>` zijn met de `<pre><code>`, anders werkt het niet
![image](https://github.com/user-attachments/assets/c5ecb8f3-2d36-4813-a214-9da549312876)

**Comment by OlivierSwaak** [comment]
Ik probeerde het einde van de `</p>` te 'inserten' om te kijken of het zo werkte
![image](https://github.com/user-attachments/assets/05b7fc00-e4b2-4234-8d36-21de3f25eb6d)
Helaas wordt elke `<` vervangen met `&lt;` en `>` met `&gt;`
![image](https://github.com/user-attachments/assets/bbf3486c-d358-4b29-ab3d-57da303ef710)

**Comment by OlivierSwaak** [comment]
![image](https://github.com/user-attachments/assets/7a97f853-b08f-4ee1-81ee-6a29de20b8f4)
Het is me nu gelukt om het in een code-block te krijgen door via lumi.education de codeblock die ik bij https://github.com/NatuurkundePracticumAmsterdam/ecpc/issues/52#issuecomment-2286642458 had gekregen te kopieren en de tekst aan te passen. Het rendert gelukkig wel de tekstblokjes. Helaas moet hierna `<pre>` nog handmatig worden toegevoegd aan de code willen we een volledig testblok hebben.

**Comment by OlivierSwaak** [comment]
Ik heb de h5p geconvert naar html en door wat dingen in het html-bestand aan te passen het volgende element ervan gemaakt:
![Image](https://github.com/user-attachments/assets/5dbd0fc6-2e77-46f2-b1f4-fba9401883c2)

Dit ziet er redelijk uit met wat we proberen te bereiken, alleen zijn er twee downsides:
1. Momenteel bevat het niet de embedding die een normaal h5p element zou hebben. Dit komt hoogstwaarschijnlijk door het exporteren van h5p in Lumi en kan worden verholpen als het h5p element wordt gehost ergens anders (de moodle server uit https://github.com/NatuurkundePracticumAmsterdam/ecpc/issues/52#issuecomment-2275769132), maar dan kunnen we niet handmatig de html aanpassen als we het als h5p hosten. Dit probleem kwamen we ook tegen bij de flashcards in #52.
1. Als we het handmatig moeten aanpassen om er uit te zien als wat we willen, dan verliezen we de shareability van het h5p element. We kunnen nog steeds natuurlijk de h5p op de github zetten als een basis die gebruikt kan worden door anderen, met enige aanpassingen, maar het zou natuurlijk ideaal zijn als het h5p element zelf de codeblocks aankan. Dit probleem hebben we wederom met de flashcards in #52. Ik zal hier meer onderzoek naar doen.

**Comment by OlivierSwaak** [comment]
Er is een manier om direct de codeblocks te krijgen, maar ik kan het alleen vinden voor h5p.com en weet niet hoe we dat moeten doen voor Moodle of voor Lumi, daar zal ik een andere keer naar kijken
https://help.h5p.com/hc/en-us/articles/7506873236381-Code-snippets-in-H5P

**Comment by AnneliesVlaar** [comment]
Ziet er niet aantrekkelijk uit. Gaan we niet mee verder

**Comment by AnneliesVlaar** [comment]
Ziet er niet aantrekkelijk uit. Gaan we niet mee verder

**Comment by AnneliesVlaar** [comment]
heropenen om goed te sluiten

**Comment by AnneliesVlaar** [comment]
won't fix
