### ISSUE TITLE
PySide6 documentatie

### ISSUE THREAD

**Issue by AnneliesVlaar** [NatuurkundePracticumAmsterdam/ecpc#28]
Een nieuwe repository maken waarin we een deel van PySide6 uitgebreid documenteren.

**Comment by AnneliesVlaar** [comment]
bekijk mogelijkheden voor automatische documentatie vanuit docstrings

**Comment by OlivierSwaak** [comment]
Kijk naar documentatiestijlen (bijvoorbeeld NumPy)

**Comment by OlivierSwaak** [comment]
Ik zal naar verschillende documentaties kijken van packages die ik door de jaren heen heb gebruikt om te kijken hoe het er uit ziet en hoe makkelijk dingen te begrijpen zijn.
De packages die ik ga onderzoeken zijn:
- [ ] NumPy
- [ ] pandas
- [ ] h5py
- [ ] pytorch (niet dat ik er veel van kan herinneren)
- [ ] openpyxl
- [ ] en natuurlijk: PySide

Ik hoop dat deze packages van verschillende groottes zijn (numpy als een wat bekendere package en openpyxl als een iets obscuurdere)

**Comment by OlivierSwaak** [comment]
# NumPy
![Image](https://github.com/user-attachments/assets/4d75a07e-b9a6-4ea5-9aeb-a3cf9a3a0c41)
Het fijne aan de NumPy documentatie is dat het is opgesplitst in guides voor verschillende doelgroepen: voor absolute beginners, voor mensen die een gedetailleerde manual willen, voor als je alleen maar wil weten hoe je die ene functie moest gebruiken maar niet zo zeer uitleg nodig hebt en als je daadwerkelijk wil meehelpen met het project.

## Absolute beginner's guide
![Image](https://github.com/user-attachments/assets/6679bb26-d0af-48aa-851d-b4bebd793a61)
Deze geeft de absolute basics: hoe installeer je het, hoe werkt de guide, wat zijn arrays, hoe werken basic operaties. Dit is heel handig voor onze documentatie. Hier kunnen we de essentiële dingen neerzetten die je nodig hebt: de setup, hoe je designer opstart, hoe de basic structuur werkt met de window, vboxes en hboxes. Dat soort dingen.

## User guide
![Image](https://github.com/user-attachments/assets/f511d75b-caff-447d-8858-d3419ff3f83c)
De user guide is gewoon de hele guide (inclusief de beginner's guide).

![Image](https://github.com/user-attachments/assets/1e496e7e-d881-43da-9d45-1c0323a5b5d4)
Deze guide staat vol met tutorials hoe je dingen moet doen.

![Image](https://github.com/user-attachments/assets/19209535-eb48-485a-867d-5d40379d5236)
De pagina navigation op de linkerkant en de navigation tussen de kopjes van de pagina aan de rechterkant zorgen zeker voor een grotere documentatie zoals dit voor meer structuur, zodat de navigatie aan de linkerhand niet opblaast. We moeten kijken welke we fijner vinden: deze manier van navigatie of de navigatie van de ECPC handleiding (zie foto hieronder). Dit hangt volledig af van de grootte van de documentatie.
![Image](https://github.com/user-attachments/assets/ce7a2304-731d-4b9e-ba66-ae2899e891b4)

## API reference
![Image](https://github.com/user-attachments/assets/219bab78-5791-4853-9411-6a80cca6fae9)
Dit is wat je meestal gaat gebruiken. Je wil weten 'hoe werkt deze functie ook al weer?', dit kan je opzoeken in de API reference. 
![Image](https://github.com/user-attachments/assets/e89e0e57-06bf-444c-84a6-3c47b5463c16)
Hier staan de parameters, het doel en wat voorbeelden van de functies uitgelegd.

## Contributors guide
![Image](https://github.com/user-attachments/assets/764cd1ab-c394-4c50-a724-ce774ba07a77)
Dit is wat minder nodig voor ons project aangezien we niet helpen met het contributen aan PySide6. Als we ooit een fork willen maken, dan misschien wel, maar voor nu kunnen we dit over het hoofd zien.

## Conclusies
De structuur van de NumPy documentatie is vrij overzichtelijk. We kunnen het beste dus de documentatie opsplitten in: basics, tutorials en een referentie voor de verschillende functies/methodes/classes van PySide6. Verder moeten we nadenken over de navigatie of we dit op de NumPy wijze willen doen of de wijze van de huidige ECPC handleiding.

**Comment by OlivierSwaak** [comment]
# pandas
![Image](https://github.com/user-attachments/assets/c94f327b-09d6-4447-81e3-c43fd8196cff)
De pandas documentatie ziet er ongeveer hetzelfde uit als de NumPy documentatie, met dezelfde structuur. Misschien hebben ze dezelfde generator gebruikt. 

![Image](https://github.com/user-attachments/assets/b1af7180-10b1-4ca2-820b-65fe32cd8316)
De dark mode van pandas maakt sommige tekst wel een beetje onleesbaar, maar dat is nu niet belangrijk.

![Image](https://github.com/user-attachments/assets/af383b8b-23ad-47ea-9df5-fee180ce695c)
Het lijkt overal dezelfde structuur te hebben als NumPy, dus ik heb hier niet zo veel meer over te zeggen.
Wat ik wel fijn vind is dat ik gelijk alle tutorials in de navigation bar kan vinden en zo sneller ben bij waar ik moeite mee heb.
Dit komt waarschijnlijk omdat pandas wat kleiner is dan NumPy, maar ik vind het nog steeds fijner dat er minder lagen in de navigatie zitten.

## Build manier
Numpy:
![Image](https://github.com/user-attachments/assets/e49d96d0-6e97-4669-aef0-0ca656ee6395)
pandas:
![Image](https://github.com/user-attachments/assets/5665e4da-38ec-49d0-acb1-d290a995efce)

Dus de Numpy en pandas documentaties zijn allebei gemaakt met Sphinx (https://www.sphinx-doc.org/en/master/), net zoals de officiele Python documentatie dus dit lijkt me handige software om dit mee te doen. Nu hopen dat de Sphinx documentatie goed is...

## Conclusies
pandas lijkt veel op NumPy. Minder levels in de documentatie maken de documentatie overzichtelijker. Sphinx kan naar gekeken worden als software om onze documentatie te maken.

**Comment by OlivierSwaak** [comment]
# h5py

![Image](https://github.com/user-attachments/assets/85ddb732-5b5e-4223-9d0b-710ae0c2babd)
De h5py documentatie maakt gebruik van een vrij bekende theme van ReadTheDocs die je vrij vaak tegenkomt bij documentatie.
Ik vind hem persoonlijk minder duidelijk dan de structuur en theme die NumPy en pandas gebruikten.

![Image](https://github.com/user-attachments/assets/a6e286d9-680a-422c-9627-6fdfb4a5550c)
Weer zijn er iets te veel lagen in de documentatie wat navigatie wat minder maakt.

![Image](https://github.com/user-attachments/assets/2882b6e6-5154-4f1b-a3fc-6b68c78e2a1b)
Ik ben wel blij met quick start guides, wat pandas en NumPy ook hadden met de 'absolute beginner's guide'.

**Comment by OlivierSwaak** [comment]
# PyTorch
![Image](https://github.com/user-attachments/assets/af33e466-f8b6-4aad-bc8c-25d938d36a1f)
Bij de PyTorch documentatie hebben ze vooral references en hier en daar een 'tutorial'.

![Image](https://github.com/user-attachments/assets/e4cf614e-65ba-490f-9b5b-6173ea6e3563)
Wat ik wel jammer vind aan de stijl die ze hier gebruiken is dat het lastig te zien is dat 'Using the visualizer' een subsectie is en niet een pagina op zich:
![Image](https://github.com/user-attachments/assets/f215f512-ea9f-4971-8d58-ced6c9f72af2)


## Conclusies
Voor wat technischere packages kan dit misschien beter zijn om gewoon gefocust te zijn op references. Zo kan je wel makkelijker de documentatie snel opmaken, maar ik denk we voor onze documentatie, als we het willen gebruiken voor o.a. ECPC, we vooral voorbeelden willen hebben en vooral alles in context willen plaatsen.

**Comment by OlivierSwaak** [comment]
# openpyxl

https://github.com/user-attachments/assets/9b466469-6a8f-44a3-b733-bdf0d778d7da

Dit laat zien dat we niet gelijk onze eigen theme zouden willen maken...
Ook vind ik het jammer dat elke tutorial op een andere pagina staat en niet te bereiken valt via de homepage. Dus om te weten welke tutorials ze hebben moet je ze allemaal doorzoeken.

## Conclusies
Voor documentatie om veel gebruikt te worden moet het er aantrekkelijk uitzien (maar het is niet nodig om het wiel opnieuw uit te vinden) en makkelijk navigeerbaar zijn.

**Comment by OlivierSwaak** [comment]
# [PySide6](https://doc.qt.io/qtforpython-6/index.html)
![Image](https://github.com/user-attachments/assets/81f48a9a-126e-49f4-b27c-99f418ca4abe)
Hier splitten ze weer alles op, dus je hebt een apart kopje voor de API reference, voor als je al weet wat je zoekt:
![Image](https://github.com/user-attachments/assets/bfae92d3-fc31-47eb-9c7a-0ff4df47834d)
en een apart kopje voor tutorials:
![Image](https://github.com/user-attachments/assets/9c8e42ac-ffc1-44a4-a4a8-1f9b37c7ddf3)

Ik vind de documentatie er visueel goed uitzien ([theme](https://github.com/pradyunsg/furo)) en deze afsplitsing is weer goed, alleen er is gewoon te veel. Het is een vrij groot project met veel dingen er in. Bij dit soort packages is het belangrijk om een goede search-functie te hebben. Alleen bezwijkt de gebruiksvriendelijkheid een beetje onder het gewicht van het project.

## Gebruikersvoorbeeld
Wil je bijvoorbeeld iets opzoeken over een ComboBox, dan kan je de searchbox gebruiken:
![Image](https://github.com/user-attachments/assets/553513b8-5269-457f-a54b-075c8517b2d9)

### Optie 1
Je wordt dan of geleid naar een overview van input methods, waar kort staat aangegeven wat een ComboBox is,
![Image](https://github.com/user-attachments/assets/57ab874c-6da6-4ff6-8056-1394467c0d67)
waar ComboBox verwijst naar een [andere documentatie](https://doc.qt.io/qt-6/qml-qtquick-controls-combobox.html):
![Image](https://github.com/user-attachments/assets/a9a60cdc-ebd2-494d-a6bf-59a3676670b7)
Ik kan me herinneren dat deze tweede documentatie iets fijner te gebruiken was omdat er wat meer voorbeelden tussen stonden, maar het is wel vervelend dat de main documentatie voor je package een andere documentatie nodig heeft om te werken. Ook al is deze documentatie niet gemaakt voor Python, maar voor (volgens mij) C++, vond ik hem de vorige twee jaar fijner te gebruiken dan de PySide6 documentatie.

### Optie 2
De andere optie is de daadwerkelijke Python class gebruiken als referentie. 
![Image](https://github.com/user-attachments/assets/7fe0bc37-31f2-4547-9f5d-1b8295415787)
Hier zien we wel gelijk de bloatedness van PySide. Er zijn gewoon zo veel dingen te doen met PySide, dit is niet zozeer iets slechts, maar het zorgt wel dat het minder gebruiksvriendelijk is. 

## Conclusie
Ik heb zelf niet een heel groot probleem met de PySide6 documentatie, maar ik denk dat het wel handig is als er een 'samenvatting' van wordt gemaakt, zodat het makkelijker te gebruiken is en je sneller de basis-dingen kan doen, maar misschien helpen de tutorials die in de documentatie staan hier al mee. Als er bepaalde dingen zijn die wat minder zijn aan de PySide6 documentatie die ik heb gemist, plaats ze ook onder deze issue, zodat we een beter beeld hebben wat we proberen te verbeteren.

Verder willen we wel dat de documentatie self-sufficient is en losstaat van de PySide6 documentatie, dus het is misschien niet handig om dezelfde stijl te gebruiken.

**Comment by OlivierSwaak** [comment]
@AnneliesVlaar en @davidfokkema jullie hebben misschien een beter gevoel voor waarom de PySide6 documentatie minder goed werkt t.o.v. bijvoorbeeld de NumPy documentatie.

**Comment by AnneliesVlaar** [comment]
Documentatie wordt gemaakt in een nieuwe repository: https://github.com/NatuurkundePracticumAmsterdam/PySide6-compact-documentation
