### ISSUE TITLE
Terminal run-knop developen

### ISSUE THREAD

**Issue by OlivierSwaak** [NatuurkundePracticumAmsterdam/ecpc#34]
Voor de run knop bij terminals een enter icoontje gebruiken en deze na het commando zetten.

_Originally posted by @OlivierSwaak in https://github.com/NatuurkundePracticumAmsterdam/ecpc/issues/17#issuecomment-2222509475_
            
Develop een run-knop, net zoals in https://github.com/NatuurkundePracticumAmsterdam/ecpc/issues/2 voor terminal input/outputs. 
Het liefste als een enter icoontje aan het einde van het commando.

**Comment by OlivierSwaak** [comment]
Ik heb bij poetry about de output toegevoegd (met de kleuren waarmee poetry het teruggeeft).
Omdat binnen codeblocks fontawesome icoontjes als letterlijke tekst worden gezien (oftewel in het codeblock komt gewoon te staan ':fontawesome-arrow-turn-down:'), heb ik het enter icoontje als een svg toegevoegd, waardoor het wel kan worden gebruikt.
Daarna roteer ik het icoontje met 90 graden, aangezien het icoontje wat daadwerkelijk op 'enter' lijkt achter een paywall zit, maar eentje die daarop lijkt, maar de verkeerde kant op staat, niet (https://fontawesome.com/icons/arrow-turn-down?f=classic&s=solid).

![Image](https://github.com/user-attachments/assets/a8d9de1e-76a1-4695-8498-161bc10edf9c)

**Comment by OlivierSwaak** [comment]
Hoveren over het icoontje verandert de kleur nog niet, dus we gaan waarschijnlijk binnen de svg de kleur moeten aanpassen niet van de hele button.

![Image](https://github.com/user-attachments/assets/f4a11c29-a3bf-4ea7-a74f-ba7793aaeff2)

En voor de reload knop gaan we weer de losse svg moeten gebruiken

![Image](https://github.com/user-attachments/assets/4e810a5b-ded4-4e1d-9710-26125eb2f125)

**Comment by OlivierSwaak** [comment]
Nu is de reload-knop ook een svg.

![Image](https://github.com/user-attachments/assets/bd6aadf8-8796-48b4-9d5d-b4bf27abbd92)

Hij voelt een beetje groot en hij ziet er scherper uit dan de enter-knop. Ik zal kijken of ik de enter-knop nog scherper kan maken.

![Image](https://github.com/user-attachments/assets/42d69181-26b3-4700-ba35-58af1c975651)

**Comment by OlivierSwaak** [comment]
De kleur van de SVG wordt nu aangepast als er overheen wordt gehoverd.

https://github.com/user-attachments/assets/d9315c35-fac7-4742-a046-8cea95e065c8

**Comment by OlivierSwaak** [comment]
Met de CSS property ```shape-rendering: crispEdges;``` wordt de enterknop wat scherper gerenderd.

![Image](https://github.com/user-attachments/assets/358b0c6b-80f6-428b-8314-edb14deb3ed4)

De SVG is hier en daar wat dunner door deze nieuwe render-techniek, maar hij ziet er wel scherper uit.

**Comment by OlivierSwaak** [comment]
Ik heb een snippet gemaakt voor deze run-knop, hij staat nu in hetzelfde json document als de andere en kan volledig in markdown.json worden gekopieerd. (File > Preferences > Configure User Snippets en zoek voor markdown.json)

![Image](https://github.com/user-attachments/assets/eeeb5ec8-6e6a-4c1e-a5c6-66d7a8b67d81)

**Comment by OlivierSwaak** [comment]
De gegeven output is wel een beetje een spoiler voor de opdracht 'poetry about', maar dan moet de opdracht worden gereworked.

![Image](https://github.com/user-attachments/assets/5b5d237d-e7c0-4074-a8f0-ccab60dd487f)

**Comment by OlivierSwaak** [comment]
Na het reviewen van de terminal run-knop kan deze worden geïmplementeerd in de rest van de handleiding.

**Comment by OlivierSwaak** [comment]
Zal ik het voor nu dan weer weghalen?

**Comment by AnneliesVlaar** [comment]
> Zal ik het voor nu dan weer weghalen?

Ja dat is goed, als blijkt dat we het op een punt echt nodig gaan hebben kunnen we altijd nog veranderen.

**Comment by AnneliesVlaar** [comment]
> Done :). Zag de knop zelf er wel goed uit?

We voegen wel veel toe (draaien renderen) voor een knopje. Het is ook idd erg dun. We gebruiken voor andere icoontjes ook material ipv fontawesome. Ik ga die aanpassen en dan zien of dat beter is.

**Comment by AnneliesVlaar** [comment]
fontawesome:
![image](https://github.com/user-attachments/assets/0186367d-3636-47ff-bab2-72fc94473170)

material:
![image](https://github.com/user-attachments/assets/79bf147f-3522-4994-bc33-6328541c2daa)

**Comment by OlivierSwaak** [comment]
Ziet er goed uit. Hoeven we aangezien het material is nu geen aparte svg te renderen? Of is het gewoon een shortcut naar de svg?

**Comment by AnneliesVlaar** [comment]
> Ziet er goed uit. Hoeven we aangezien het material is nu geen aparte svg te renderen? Of is het gewoon een shortcut naar de svg?

shortcut naar de svg, ik zal hem even pushen

**Comment by OlivierSwaak** [comment]
Aah maar het is een simpelere svg, logisch.
