### ISSUE TITLE
Groen map/bestand icoontje voor nieuw toegevoegde items in mappenboom

### ISSUE THREAD

**Issue by AnneliesVlaar** [NatuurkundePracticumAmsterdam/ecpc#36]

**Comment by OlivierSwaak** [comment]
In 'Basiskennis Python' heb ik onder 'F-strings, variabelen en input' voorbeelden gemaakt voor groen map/bestand icoontje voor nieuwe toegevoegde items. 

![Image](https://github.com/user-attachments/assets/1c444c4c-f91a-44a7-9730-2b0697614b68)

Voor deze opdracht specifiek zou natuurlijk de ECPC map gewoon zwart blijven, maar dit was een handige plek om wat voorbeelden te plaatsen.
Ik ben zelf een voorstander van het gebruik van de ingevulde icoontjes (3.) aangezien de kleur hier veel beter te zien is.
Ik zal kijken hoe het er uit ziet in de mappenboom, maar dit laat ook wel zien dat we het ook buiten de mappenboom kunnen gebruiken.
Ik denk dat het handig is om net zoals bij #2 en #34 we een aparte issue aan te maken voor het implementeren van deze icoontjes, aangezien het vinden van elke plek waar het kan worden gebruikt even zal duren.

**Comment by OlivierSwaak** [comment]
We zouden ook de tekst zelf groen kunnen maken, maar ik weet niet of ik hier fan van ben.

![Image](https://github.com/user-attachments/assets/2a303ea5-c12b-460e-97fd-ba8167108530)

**Comment by OlivierSwaak** [comment]
Ik heb de mappenboom omgezet naar de nieuwe stijl voor poetry new --src easystat

![Image](https://github.com/user-attachments/assets/e2234ec6-214e-48ba-8a16-118bda5cfc00)

Aangezien we hier nieuwe mappen aanmaken, is het dan logisch om ze allemaal groen te maken?

**Comment by OlivierSwaak** [comment]
> Ik heb de mappenboom omgezet naar de nieuwe stijl voor poetry new --src easystat
> 
> ![Image](https://private-user-images.githubusercontent.com/90635681/348307334-e2234ec6-214e-48ba-8a16-118bda5cfc00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3OTcxNDIsIm5iZiI6MTcyMDc5Njg0MiwicGF0aCI6Ii85MDYzNTY4MS8zNDgzMDczMzQtZTIyMzRlYzYtMjE0ZS00OGJhLThhMTYtMTE4YmRhNWNmYzAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDE1MDcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkOTM1ZjY0NWFlZmQwMjIyMjY5ZjI3OTljMjdjNzhjZjU3OWE3MDEzMjEwZGI2NmUxY2Y2YzVjZmI5MmIwNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RAxbxMULdhafVP-kAjWX77RmRjLxHHLarWs1T6o2yRE)
> 
> Aangezien we hier nieuwe mappen aanmaken, is het dan logisch om ze allemaal groen te maken?

Dit is als ze allemaal groen zijn.

![Image](https://github.com/user-attachments/assets/0a936216-2f92-47eb-810c-bf83e0908be7)

**Comment by OlivierSwaak** [comment]
En dan de opdracht waar deze issue origineel over ging gerewrite om gebruik te maken van deze nieuwe icoontjes:

![Image](https://github.com/user-attachments/assets/38628d35-9830-4fa9-9909-18773c725821)

![Image](https://github.com/user-attachments/assets/75349af6-1c29-4fc9-8fd5-c2f04ae83eb7)

En als we klikken op de enter knop:

![Image](https://github.com/user-attachments/assets/a687d27b-cac2-47a5-9015-4c6f45029d99)

(De visuals van de terminal knop werken niet, omdat #39 nog niet is afgewerkt)
Het is nu duidelijker waar de files aangemaakt moeten worden.

**Comment by OlivierSwaak** [comment]
De voetnoot in de titel van de tabs werkt helaas niet aangezien de click event van de tab voorrang krijgt. 
Deze voetnoot moet dus nog ergens anders gezet worden, maar ik denk dat deze opdracht nu al goed laat zien wat er mogelijk is met de groene icoontjes.

**Comment by AnneliesVlaar** [comment]
> De voetnoot in de titel van de tabs werkt helaas niet aangezien de click event van de tab voorrang krijgt. Deze voetnoot moet dus nog ergens anders gezet worden, maar ik denk dat deze opdracht nu al goed laat zien wat er mogelijk is met de groene icoontjes.

Welke voetnoot werkt nu niet?

**Comment by AnneliesVlaar** [comment]
> We zouden ook de tekst zelf groen kunnen maken, maar ik weet niet of ik hier fan van ben.
> 
> ![Image](https://private-user-images.githubusercontent.com/90635681/348301929-2a303ea5-c12b-460e-97fd-ba8167108530.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNDU5ODQsIm5iZiI6MTcyMTA0NTY4NCwicGF0aCI6Ii85MDYzNTY4MS8zNDgzMDE5MjktMmEzMDNlYTUtYzEyYi00NjBlLTk3ZmQtYmE4MTY3MTA4NTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDEyMTQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiMzI0NmU3YTIxY2NiMTI1OTFiNTgyZGM3ZGJlYTA3YjYzOGUzNjQyMGRjYTI2ODc5YmI3Mzk4MDM4ZDNkY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QdCQd4fdZqDuFZj9mtJUpkmaOIUrOTHzy7upixBslTE)

De tekst groen maken ben ik ook geen voorstander van, laten we dat zwart houden. Verder denk ik dat de open groen icoontjes beter zijn om te gebruiken omdat het geheel er dan iets rustiger uitziet.

**Comment by OlivierSwaak** [comment]
> > De voetnoot in de titel van de tabs werkt helaas niet aangezien de click event van de tab voorrang krijgt. Deze voetnoot moet dus nog ergens anders gezet worden, maar ik denk dat deze opdracht nu al goed laat zien wat er mogelijk is met de groene icoontjes.
> 
> Welke voetnoot werkt nu niet?

Nummer 7, die binnen de titel staat, je kan er niet op drukken, want dan denkt mkdocs dat je naar die tab wil switchen.

**Comment by AnneliesVlaar** [comment]
> > > De voetnoot in de titel van de tabs werkt helaas niet aangezien de click event van de tab voorrang krijgt. Deze voetnoot moet dus nog ergens anders gezet worden, maar ik denk dat deze opdracht nu al goed laat zien wat er mogelijk is met de groene icoontjes.
> > 
> > 
> > Welke voetnoot werkt nu niet?
> 
> Nummer 7, die binnen de titel staat, je kan er niet op drukken, want dan denkt mkdocs dat je naar die tab wil switchen.

Daar zouden we ook een [annotation](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-annotations) van kunnen maken. Zou wel mooi zijn als we dat ook dan vaker gaan gebruiken in de handleiding.

Laten we de voetnoot voorlopig als gewone tekst onder de tabjes neerzetten. Wil jij dat doen @OlivierSwaak ?

**Comment by OlivierSwaak** [comment]
Ik heb er een annotation van gemaakt. Het viel vrij snel te implementeren.

**Comment by AnneliesVlaar** [comment]
> Ik heb er een annotation van gemaakt zodat we konden zien hoe dat er uit zag. Het viel vrij snel te implementeren.

Als we annotations in code maar 1 keer in de handleiding gebruiken dan vrees ik dat de studenten het sneller over het hoofd zien.  Daarom liever nu als gewone tekst eronder.
Later kunnen we kijken of annotations een toegevoegde waarde hebben en het op meer plekken in de handleiding inzetten.

**Comment by OlivierSwaak** [comment]
Oke, de annotation is nu weg.
Ik zal even snel de andere mock-ups weghalen.
Willen we bij poetry new de hele mappenboom groen maken?

![Image](https://github.com/user-attachments/assets/823eb73d-1d50-4e5f-9d4d-9b654b8d394a)

**Comment by AnneliesVlaar** [comment]
> Oke, de annotation is nu weg. Ik zal even snel de andere mock-ups weghalen. Willen we bij poetry new de hele mappenboom groen maken?
> 
> ![Image](https://private-user-images.githubusercontent.com/90635681/348725152-823eb73d-1d50-4e5f-9d4d-9b654b8d394a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNTE0MTUsIm5iZiI6MTcyMTA1MTExNSwicGF0aCI6Ii85MDYzNTY4MS8zNDg3MjUxNTItODIzZWI3M2QtMWQ1MC00ZTVmLTlkNGQtOWI2NTRiOGQzOTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDEzNDUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5YzAyYWJjNWIxMzBiNDZjYmNkZTRlZWE4ODk2N2Q4ZjhhMTU4YjI1NTdmY2FmM2IzNTQxZmJiZTM1ZWE5NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OWlUDzAY_jY_lY64_rYjTDgvIglPQ0FpgRxbob9Uu1Y)

Ja, de hele boom mag groen. Als we ook de ECPC map als bovenste map neerzetten dan is die als enige zwart.

**Comment by OlivierSwaak** [comment]
![Image](https://github.com/user-attachments/assets/cf246f87-a140-4dac-9084-bb4f369f7bc4)

Met de ECPC map ziet het er zo uit.
Willen we voor de ECPC map nog een 'L' hebben en alles met een tab naar rechts verschuiven om te laten zien dat de ECPC map zelf ook in een andere map zit?
Of is dit duidelijk genoeg?

**Comment by AnneliesVlaar** [comment]
> ![Image](https://private-user-images.githubusercontent.com/90635681/348729046-cf246f87-a140-4dac-9084-bb4f369f7bc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNTE5NjMsIm5iZiI6MTcyMTA1MTY2MywicGF0aCI6Ii85MDYzNTY4MS8zNDg3MjkwNDYtY2YyNDZmODctYTE0MC00ZGFjLTkwODQtYmI0ZjM2OWY3YmM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDEzNTQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyYzczY2YzM2ZmZDFkYzYzMzc3ZWI4ODE3YWMxZmRkMzQzZDkzOWRjY2E2ODc0NTgyMTE0MDllN2MxNmZkNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KiWte9u0IDI7mFgfXUWS8Y9YFQlIZE99cIImPdxDa3w)
> 
> Met de ECPC map ziet het er zo uit. Willen we voor de ECPC map nog een 'L' hebben en alles met een tab naar rechts verschuiven om te laten zien dat de ECPC map zelf ook in een andere map zit? Of is dit duidelijk genoeg?

Dit is duidelijk genoeg, waar leg je anders de grens? Bij de eerste opdracht 'aanmaken van ECPC' map kunnen we dat natuurlijk wel doen.

**Comment by OlivierSwaak** [comment]
Als de rewrite bij poetry voor nu goed genoeg is, dan kunnen we de branches gaan mergen.

**Comment by AnneliesVlaar** [comment]
> Als de rewrite bij poetry voor nu goed genoeg is, dan kunnen we de branches gaan mergen.

Ik ga daar deze week naar kijken en dan mergen
