### ISSUE TITLE
Terminal run-knop implementeren in de rest van de handleiding

### ISSUE THREAD

**Issue by OlivierSwaak** [NatuurkundePracticumAmsterdam/ecpc#38]
> Na het reviewen van de terminal run-knop kan deze worden geïmplementeerd in de rest van de handleiding.  

 _Originally posted by @OlivierSwaak in [#34](https://github.com/NatuurkundePracticumAmsterdam/ecpc/issues/34#issuecomment-2225625913)_

> Ik heb een snippet gemaakt voor deze run-knop, hij staat nu in hetzelfde json document (docs/assets/markdown.json) als de andere en kan volledig in markdown.json worden gekopieerd. (File > Preferences > Configure User Snippets en zoek voor markdown.json)
> Deze kan dan worden aangeroepen door terminal in te typen en dan ctrl+spacebar in te drukken.

 _Originally posted by @OlivierSwaak in [#34](https://github.com/NatuurkundePracticumAmsterdam/ecpc/issues/34#issuecomment-2225611095)_

Voorbeeld staat in 'Poetry' bij de opdracht 'poetry about'.

**Comment by OlivierSwaak** [comment]
Als er wordt hovered over een footnote, dan verschijnt er ook zo'n entertekentje.
![image](https://github.com/user-attachments/assets/8da7a981-1f9f-4c24-9127-a45c97149d53)
Blijkbaar is dit gewoon een unicode character die we dus ook zouden kunnen gebruiken als enter knop '↩'

**Comment by AnneliesVlaar** [comment]
@Etterbak Ik heb een paar terminal runknopjes omgezet naar script runknopjes en ga de branch mergen!
