### ISSUE TITLE
voeg rand toe rondom run-knop in- en uitvoer

### ISSUE THREAD

**Issue by AnneliesVlaar** [NatuurkundePracticumAmsterdam/ecpc#48]
Ten opzichte van de terminal-knop zag de run-knop er als 3 losse elementen uit:

![image](https://github.com/user-attachments/assets/6b91ff80-0a11-48b4-877f-65fd58a2748d)

We kunnen er proberen een geheel van te maken door er een randje omheen te zetten:

![image](https://github.com/user-attachments/assets/ffa8726d-6157-4479-acdf-b3ad55d163ca)

**Comment by OlivierSwaak** [comment]
Dit maakt het zeker duidelijker dat de elementen bij elkaar horen. Ziet er een stuk beter uit.

**Comment by OlivierSwaak** [comment]
Kijk naar een outline playknop en niet bolde tekst zodat het meer een geheel vormt met het script en de output

**Comment by OlivierSwaak** [comment]
Padding aan de onderkant hetzelfde als aan de zijkanten

**Comment by OlivierSwaak** [comment]
Nieuwe icon voor de play-button

![Image](https://github.com/user-attachments/assets/72c77366-6202-44fe-af2f-2b466fcc6758)

**Comment by OlivierSwaak** [comment]
> Padding aan de onderkant hetzelfde als aan de zijkanten

Ik denk dat de padding aan de onderkant de margin is van een codeblock, aangezien het minder dan een regel is, dus ik weet niet of we dan makkelijk kunnen oplossen.

**Comment by AnneliesVlaar** [comment]
> Nieuwe icon voor de play-button
> 
> ![Image](https://private-user-images.githubusercontent.com/90635681/355170422-72c77366-6202-44fe-af2f-2b466fcc6758.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4ODE2NTAsIm5iZiI6MTcyMjg4MTM1MCwicGF0aCI6Ii85MDYzNTY4MS8zNTUxNzA0MjItNzJjNzczNjYtNjIwMi00NGZlLWFmMmYtMmI0NjZmY2M2NzU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDE4MDkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxMjY5NjIxMGJiODRkNjI1MDlhMjJhMTg0ODE5OTY1N2JmOGI2ODAzNTdiOGQ5ZmVlMjk1ZjAwNTdiN2M2MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AQvXhYNJT2rHBze88Ps23JNrtHm1c-3X64vpTnDx3jc)
> 
> Het lijkt nu ook meer op de play-knop van VSCode. Het voelt meer een geheel met de rest van de tekst.

Ik vond de hoeken van de play-knop erg scherp. We kunnen ze ronder maken:

![image](https://github.com/user-attachments/assets/8e40f652-fbff-4671-83ad-8e64e6c3aca9)

Dit heb ik gedaan met https://iconsvg.xyz/
```
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#000000" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><polygon points="5 3 19 12 5 21 5 3"></polygon></svg>
```
en de kleur wordt weer groen met:
```
svg.run:hover {
    stroke: green;
}
```

**Comment by AnneliesVlaar** [comment]
> Verder kunnen we kijken of we de border misschien of iets dikker maken of net een andere kleur maken. Op een van mn monitoren ziet het er heel duidelijk uit, maar op de andere kan ik hem amper zien, dus ik weet niet wat het geval gaat zijn op de labcomputers.

Dikker vind ik zelf niet zo mooi, dan wordt het al gauw bonkig. 
Als de kleur er teveel uit springt kan het weer afleiden, maar is #efefef iets?

![image](https://github.com/user-attachments/assets/9523f7ea-100c-48c7-b016-6adf5f341556)

**Comment by OlivierSwaak** [comment]
> > Nieuwe icon voor de play-button
> > ![Image](https://private-user-images.githubusercontent.com/90635681/355170422-72c77366-6202-44fe-af2f-2b466fcc6758.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4ODE2NTAsIm5iZiI6MTcyMjg4MTM1MCwicGF0aCI6Ii85MDYzNTY4MS8zNTUxNzA0MjItNzJjNzczNjYtNjIwMi00NGZlLWFmMmYtMmI0NjZmY2M2NzU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDE4MDkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxMjY5NjIxMGJiODRkNjI1MDlhMjJhMTg0ODE5OTY1N2JmOGI2ODAzNTdiOGQ5ZmVlMjk1ZjAwNTdiN2M2MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AQvXhYNJT2rHBze88Ps23JNrtHm1c-3X64vpTnDx3jc)
> > Het lijkt nu ook meer op de play-knop van VSCode. Het voelt meer een geheel met de rest van de tekst.
> 
> Ik vond de hoeken van de play-knop erg scherp. We kunnen ze ronder maken:
> 
> ![image](https://private-user-images.githubusercontent.com/66774020/355200104-8e40f652-fbff-4671-83ad-8e64e6c3aca9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzEwMTgsIm5iZiI6MTcyMjkzMDcxOCwicGF0aCI6Ii82Njc3NDAyMC8zNTUyMDAxMDQtOGU0MGY2NTItZmJmZi00NjcxLTgzYWQtOGU2NGU2YzNhY2E5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA3NTE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMDdjYzg2ZWM1NWY1ZGI4NDA3NTI0NWQ1MjExYTJlOTJlODM1N2Q4ZmJkNTg2MjhiYWJkMTJiNmMxNzczOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6JIcndPH6VC9v9XMFfDu6wIHtCQkgYvRoy7yuSFupqk)
> 
> Dit heb ik gedaan met https://iconsvg.xyz/
> 
> ```
> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#000000" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><polygon points="5 3 19 12 5 21 5 3"></polygon></svg>
> ```
> 
> en de kleur wordt weer groen met:
> 
> ```
> svg.run:hover {
>     stroke: green;
> }
> ```

Ja, ziet er beter uit.

**Comment by OlivierSwaak** [comment]
> > Verder kunnen we kijken of we de border misschien of iets dikker maken of net een andere kleur maken. Op een van mn monitoren ziet het er heel duidelijk uit, maar op de andere kan ik hem amper zien, dus ik weet niet wat het geval gaat zijn op de labcomputers.
> 
> Dikker vind ik zelf niet zo mooi, dan wordt het al gauw bonkig. Als de kleur er teveel uit springt kan het weer afleiden, maar is #efefef iets?
> 
> ![image](https://private-user-images.githubusercontent.com/66774020/355205071-9523f7ea-100c-48c7-b016-6adf5f341556.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzEwMTgsIm5iZiI6MTcyMjkzMDcxOCwicGF0aCI6Ii82Njc3NDAyMC8zNTUyMDUwNzEtOTUyM2Y3ZWEtMTAwYy00OGM3LWIwMTYtNmFkZjVmMzQxNTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA3NTE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiNzNkNWU4NmU3MDVjN2QzNTM3MDExNmM3MDdjZjQ4YjI1ODUwM2U5ZTkzMmFhMTNhOTZkMzAzMjBkN2Y3YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AK60XSdhjmXYLa--Ow6nBcddIBDavLeL99WcLPOP75E)

Ik kan het verschil niet heel erg goed zien, maar ik denk dat #efefef beter is ja.
