### ISSUE TITLE
Vergelijken van terminal-script Arduino Visa

### ISSUE THREAD

**Issue by OlivierSwaak** [NatuurkundePracticumAmsterdam/ecpc#5]
Maak met bijvoorbeeld hoverevents en highlights een koppeling tussen terminal en python code Arduino Visa.

**Comment by OlivierSwaak** [comment]
Om deze vergelijking te maken wil ik graag gebruik maken van hoverevents over de pythoncode.
Het is alleen niet mogelijk om in de ``` code blocks html te gebruiken, aangezien mkdocs dit interpreteert als een stuk code die we willen weergeven. Dan zouden we een normale <code> block moeten gebruiken, alleen deze heeft niet de mooie kleurtjes.
Er zijn hier twee dingen die we kunnen doen:
1. We plaatsen een kopie van het ``` blok als een <code> blok over het ``` blok heen en zetten de opacity op 0%. Hiermee behouden we nog wel de hoverevents, maar zien we het niet.
2. We voegen de kleurtjes handmatig toe aan het <code> blok.

**Comment by OlivierSwaak** [comment]
Optie nummer 1 is heel afhankelijk van CSS en gaat te veel moeite kosten om altijd te laten werken.
![image](https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/833a4104-7745-4f4d-920f-78610018cfe3)
Hierboven zien we de de overlayed text met 50% opacity, de kleuren zijn daardoor iets donkerder.
Helaas als we inzoomen verschuift de overlay een klein beetje
![image](https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/226af5d6-3fd7-4a1a-bb58-a8f6fb7a3c00)
Ik ben bang dat dit misschien ook per monitor zal verschillen, dus, aangezien we maar twee keer de comparison gaan doen wil ik optie twee gaan proberen, wat me een beetje sneller lijkt.

**Comment by davidfokkema** [comment]
Hoe wil je dat het eruit gaat zien? Om in de syntaxblokken de syntax met de hand te gaan highlighten... En de kleine verschuiving is op zich geen probleem toch? Maar ik zie waarschijnlijk niet goed voor me wat je wilt zien.

**Comment by OlivierSwaak** [comment]
De kleine verschuiving was op zich geen probleem, alleen was ik bang dat hij eventueel groter dan klein zou worden bij sommige computers/browsers/venstergroottes. Het highlighten van de tekst met de hand is echter wel gelukt en duurde door de ingebouwde stylesheet van mkdocs niet zo lang:
![image](https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/6d350061-3d9e-4215-8dc7-831aa15d04e1)

**Comment by davidfokkema** [comment]
Oh, top. Als het maar een enkele keer hoeft...

**Comment by OlivierSwaak** [comment]
Als het goed is hoeft het maar twee keer (deze issue en https://github.com/NatuurkundePracticumAmsterdam/ecpc/issues/7 ). Als we toch merken dat het vaker moet, dan kan ik altijd de eerdere techniek gebruiken.

**Comment by davidfokkema** [comment]
Prachtig!!!! 🤯. De details CRLF / LF zijn mooi. Wat je zegt klopt helemaal. Het commando `pyvisa-shell -b py` start de shell en daarna kun je `list` doen. En `import pyvisa; rm = pyvisa.ResourceManager("@py")` doet dat ook. De `-b py` is hetzelfde als `"@py"`, het selecteert de Python backend i.p.v. bijvoorbeeld geïnstalleerde LabVIEW VISA drivers.

**Comment by OlivierSwaak** [comment]
https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/18decd36-41ec-4712-b2f8-dd032e9042b5

Dan is dit de versie waar alles in is verwerkt. 
Ik weet nog niet waar we dit precies in de handleiding kunnen doen.
Het zou eventueel kunnen worden samengevoegd met de line-for-line uitleg van het script
![image](https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/07491f64-b71a-4df9-9ff9-53ccf56838ee)
Of we houden de line-for-line en voegen het samen met 'het volledige script'. 
![image](https://github.com/NatuurkundePracticumAmsterdam/ecpc/assets/90635681/bf295961-6681-4392-ae30-31c352641ce0)
Alleen dan moeten we gaan nadenken hoe we dit dan met de run-button willen combineren (https://github.com/NatuurkundePracticumAmsterdam/ecpc/issues/2#issuecomment-2217319659).

**Comment by OlivierSwaak** [comment]
Ook highlighten in originele code

**Comment by OlivierSwaak** [comment]
Naast elkaar

**Comment by OlivierSwaak** [comment]
Extra events query IDN

**Comment by OlivierSwaak** [comment]
print identification los

**Comment by OlivierSwaak** [comment]
Nieuwe issue voor tool html
