### ISSUE TITLE
Flashcards met code-editor

### ISSUE THREAD

**Issue by AnneliesVlaar** [NatuurkundePracticumAmsterdam/ecpc#52]
Vanuit het boek Programmers Brain, ieder hoofdstuk eindigen met flashcards en naast de flashcards een editor om je antwoord even op te schrijven. Daarna zelf controlleren. 

Er bestaat al een soort code editor https://github.com/DegrangeM/H5P.CodeHighlighter
En er bestaan dialog cards. https://h5p.org/dialog-cards#example=619

**Comment by OlivierSwaak** [comment]
Kleine status update: 
Het is me gelukt om de h5p development environment op te zetten.
De mail die eerder was doorgestuurd leidde naar een release note (https://h5p.org/july-2024-release-note) die verwees naar een github pagina voor de h5p cli (https://github.com/h5p/h5p-cli).
Na deze te hebben geinstalleerd mbv de documentatie op de github pagina, en `h5p server` te hebben gerund in de command prompt, werd een development area gehost (op http://localhost:8080/dashboard).

![Image](https://github.com/user-attachments/assets/829bac57-2fcd-4d1c-8751-4a051a588336)

**Comment by OlivierSwaak** [comment]
Voor de code highlighter waren custom libraries nodig (https://github.com/DegrangeM/H5P.CodeHighlighter, https://github.com/DegrangeM/H5P-CodeMirror?tab=readme-ov-file en https://github.com/DegrangeM/H5PEditor.CodeEditor). Deze heb ik elk binnen de aangemaakte h5p environment (zie de stappen van de setup van h5p-cli) in de map libraries gezet. Vervolgens heb ik met `h5p register` al deze custom libraries geregistreerd. Ik weet niet zeker of deze stap nodig was, maar ik denk het wel. Als ik de setup nogmaals doe op mijn andere computer zal ik deze issue updaten.

**Comment by OlivierSwaak** [comment]
Binnen de h5p dev environment is het heel makkelijk om nieuwe elementen aan te maken en ze te editen.
![Image](https://github.com/user-attachments/assets/5b17f080-8f6f-48ed-9690-c5d4207823e9)
Zie hoe `h5p-code-highlighter` in het dropdownmenu staat en dus makkelijk te implementeren is.

Met deze applicatie heb ik voorbeeld flashcards voor poetry commands aangemaakt:
![Image](https://github.com/user-attachments/assets/0e087df5-a96c-48f7-a5ae-15902f526a45)
En een codehighlighter:
![Image](https://github.com/user-attachments/assets/d0e85348-819f-4f85-ad4d-3c35c7e024eb)
Alleen nu moet ik nog een manier vinden om ze te implementeren, aangezien deze environment alleen .h5p bestanden exporteert.

**Comment by OlivierSwaak** [comment]
Alleen de highlighting lijkt nog niet helemaal te werken, daar kijk ik later naar. Ik wil eerst de embedding in de handleiding werkend krijgen.

![Image](https://github.com/user-attachments/assets/81a6727a-67c2-4d4f-b4c3-3167bd81c1ab)

**Comment by OlivierSwaak** [comment]
Als we h5p elementen willen embedden moeten we ze ergens hosten of converten naar .html bestanden.
Het converten naar .html is me voor nu nog alleen gelukt voor de flashcards.
Ik wilde hiervoor eerst de Lumi Education desktop app gebruiken, alleen lukte het me niet om de geproduceerde .h5ps in te laden (van beide elementen niet).
![Image](https://github.com/user-attachments/assets/923920ca-98ee-484f-bfb5-f68f0056883e)
Gek genoeg lukt het wel om de h5p van de drag and drop exercise uit de handleiding in te laden.
![Image](https://github.com/user-attachments/assets/4ddbfead-9855-4952-a82e-8339019535c9)

**Comment by OlivierSwaak** [comment]
Maar via de webapp lukte het me wel op de h5p van de flashcards in te laden.
![Image](https://github.com/user-attachments/assets/4a5393f5-fe64-4a1a-9e99-ed3ff2ac8ab2)
Hiermee kon ik eindelijk een html bestand ervan maken
![Image](https://github.com/user-attachments/assets/432c5d20-4f76-423d-8cd3-8b3a08cbcdd0)
en hem embedden in de handleiding.
![Image](https://github.com/user-attachments/assets/91dfe587-8f6f-40fb-835d-8c16329363ca)

**Comment by OlivierSwaak** [comment]
Alleen is het me nog niet gelukt om de codehighlighter op de zelfde manier werkend te krijgen.
![Image](https://github.com/user-attachments/assets/23e870ff-3b1f-422a-b2be-0b337001789d)
Hij laat zover ik weet een errormelding zien dat de custom libraries niet worden herkend.
Ik had gehoopt dat het .h5p bestand alles bevatte, waaronder de custom libraries, maar dit is helaas niet het geval.
Nu moet ik gaan uitzoeken hoe ik deze libraries alsnog toe kan voegen aan de Lumi webapp zodat ik een html bestand kan maken.

**Comment by OlivierSwaak** [comment]
Er is via de desktop app wel een manier om libraries toe te voegen (bij de foto hieronder was de lijst eerst leeg), alleen lukte het me niet om deze daadwerkelijk toe te voegen.
![Image](https://github.com/user-attachments/assets/f6dad916-3ba8-46b4-aac5-a3c59f06e505)
Na het uploaden van de drag n drop exercise (https://github.com/NatuurkundePracticumAmsterdam/ecpc/issues/52#issuecomment-2273463981) zijn deze extra libraries erbij gekomen, dus ik zal kijken of ik dit alsnog werkend kan krijgen.

**Comment by OlivierSwaak** [comment]
Ik probeer nu handmatig de libraries toe te voegen in de roaming folder van lumi om te kijken of dit een verschil maakt
![Image](https://github.com/user-attachments/assets/5182cbe8-2e2b-4d41-9e60-8dda49d3f18f)

**Comment by OlivierSwaak** [comment]
Het uploaden van een werkende h5p installeert de juiste libraries, dus ik ga kijken of ik op een andere manier uit de dev env een h5p kan krijgen en hopelijk werkt het dan wel.
![Image](https://github.com/user-attachments/assets/9eec8080-5720-423d-8427-0f64cd992aa0)

**Comment by OlivierSwaak** [comment]
Het lukte me wel om een standaard fill in the blanks te uploaden
![Image](https://github.com/user-attachments/assets/82443926-8497-461f-af36-7868a8816954)

**Comment by OlivierSwaak** [comment]
Werkt nog steeds niet
![Image](https://github.com/user-attachments/assets/d2617691-3685-42eb-9b9a-65595af4c099)

**Comment by OlivierSwaak** [comment]
Ik probeerde een andere website te gebruiken (https://www.metaxdata.eu/h5p).
Met de dialogcards werkte het wel
![Image](https://github.com/user-attachments/assets/92795b66-cac8-45d4-ac2d-ef0f9206a353)
maar weer met de codehighlighter met de custom libraries lukte het niet
![Image](https://github.com/user-attachments/assets/60ed2c3b-2ac4-4bd4-a85c-cca90daae49b)
dus ik zal weer wat anders proberen te vinden

**Comment by OlivierSwaak** [comment]
Ik heb een forumpost van de developer gevonden waarin de libraries als een h5p file stonden (https://h5p.org/node/1142918), dus ik kon ze nu uploaden in de Lumi Desktop App.
![image](https://github.com/user-attachments/assets/0944b8b8-0116-4b47-9397-7d34e778fc16)
Nu zal ik Lumi Desktop proberen te gebruiken om een highlighter te maken en kijken of ik hem kan implementeren in de handleiding.

**Comment by OlivierSwaak** [comment]
In Lumi lijkt de highlighting wel te werken (in tegenstelling tot de h5p dev env https://github.com/NatuurkundePracticumAmsterdam/ecpc/issues/52#issuecomment-2273432502)
![image](https://github.com/user-attachments/assets/49dedf41-1142-4345-b690-658d7b2b0a15)

**Comment by OlivierSwaak** [comment]
Ik heb toen op meerdere manieren geprobeerd de h5p de hosten, maar het volgende is wat werkte.

![image](https://github.com/user-attachments/assets/8d6ef164-26ef-40ee-af6c-88fb14534cb6)
Onder 'home' heb ik in edit mode via 'add an activity or resource' een h5p element toegevoegd aan de hoofdpagina:
![image](https://github.com/user-attachments/assets/e1e1333c-1993-4333-abaf-1b3bfb943790)
**Let op:** ik probeerde dit eerst te doen door het toe te voegen aan een course (omdat ik niet wist dat je het aan de hoofdpagina kon toevoegen), maar dit werkte niet aangezien je dan bepaalde permissions nodig hebt om het te bekijken en dan kan je het niet embedden.

**Comment by OlivierSwaak** [comment]
![image](https://github.com/user-attachments/assets/99fba19e-ae4b-4dcc-9354-72e213dffdbf)
Vervolgens heb ik de default codehighlighter uit Lumi (dezelfde die ik hier heb gebruikt: https://github.com/NatuurkundePracticumAmsterdam/ecpc/issues/52#issuecomment-2275769132) toegevoegd. En de 'Allow download' en 'Embed button' aangevinkt en het element toegevoegd.

**Comment by OlivierSwaak** [comment]
Ik kan er voor nu niet meer verder aan werken, maar ben wel blij met de progressie. Dingen die nog gedaan moeten worden:
[ ] Naast elkaar zetten van de elementen. (vrij snel te doen)
[ ] Fixen dat de embedding ervoor zorgt dat er witregels onder de elementen komen.
[ ] Tekst van dialogcards formatten als er coderegels zijn.

Ik denk dat daarna het framework (met wat aanpassingen) klaar is. Het zal dan waarschijnlijk een mini-project zijn om de flashcards te bedenken.
Ik heb hiermee veel progressie gemaakt met het uitvogelen hoe h5p werkt, dus kan ik makkelijker h5p-achtige issues uitvoeren.

**Comment by OlivierSwaak** [comment]
Ik wil liever de whitespace minimaliseren, dus ik zal kijken of ik het misschien een scrollable div kan maken

**Comment by OlivierSwaak** [comment]
https://github.com/user-attachments/assets/c878e7c9-d412-4de4-bd47-ce9e1bfe36b0

Het is gelukt om het een scrollable div te maken

**Comment by OlivierSwaak** [comment]
![image](https://github.com/user-attachments/assets/6185de38-6684-4bd8-a849-9c084ec6ea2e)

Het is mogelijk om iets van een codeblock toe te voegen, dus ik ga kijken of ik divs toe kan voegen om de syntax te highlighten

**Comment by OlivierSwaak** [comment]
Ik bedenk me net, het maakt niet zoveel uit of we het kunnen syntaxhighlighten op de manier van de handleiding, als we het ook kunnen syntaxhighlighten op de manier van het h5p element. Ik zal kijken of ik ze kan samenvoegen

**Comment by OlivierSwaak** [comment]
![image](https://github.com/user-attachments/assets/5aae0bc6-788c-4bbd-b9ee-023d4065bbab)
Het is me gelukt om een texteditor als antwoord te embedden. Ik weet niet of dit het waard is. Dit zou betekenen dat een aparte h5p met die bepaalde tekst gehost moet worden voor elke individuele dialogcard (ten minste op de manier zoals ik het nu doe).
Ik zal wat cleanup doen en dan een comparison maken tussen of het embedden of gewoon een codeblok inserten.

**Comment by OlivierSwaak** [comment]
![image](https://github.com/user-attachments/assets/85415a4b-77cf-4d9c-be82-022b187fa410)
![image](https://github.com/user-attachments/assets/38909d61-52f5-419b-a631-9c2097b09d6e)
Het zetten van tekst tussen drie backticks zorgt er wel voor dat het er uit ziet als een code block, maar maakt het niet een volledige code block

**Comment by OlivierSwaak** [comment]
![image](https://github.com/user-attachments/assets/d41df62b-1ec0-490c-906d-a2c28d7a774b)
Zelfde output met `<pre><code>`

**Comment by OlivierSwaak** [comment]
Als je de codeblock wil, moet je handmatig in de html file `<pre>` voor `<code>` zetten en `</pre>` na `</code>`

**Comment by OlivierSwaak** [comment]
https://github.com/user-attachments/assets/ebe4247f-d2cd-4ad6-ab97-cdd7e2faf6f6
Showcase van beide mockups. Als we de tekst van de vraag zelf nog willen formatten is dat een andere issue.
Ik zal even een klein 'pro-con' lijstje maken voor de mockups:

# Embedded code editor
- Pro: Ziet er hetzelfde uit als de input van de student en is ook gesyntaxhighlight wat het makkelijker te vergelijken maakt.
- Con: Embedding moet handmatig gebeurd worden (handmatig aanpassen van de html).
- Con: Elk antwoord moet in een apart h5p bestand gehost worden.

# Plain code block
- Con: Ziet er niet hetzeflde uit als de input van de student en is niet gesyntaxhighlight.
- Pro: Kan worden toegevoegd door tussen drie backticks de code te zetten (https://github.com/NatuurkundePracticumAmsterdam/ecpc/issues/52#issuecomment-2286642458) of door de code tussen `<pre><code>` te zetten (misschien is alleen '`<code>`' al genoeg).
- Con: Om daadwerkelijk een codeblock er uit te krijgen moet handmatig in de html het codeblock omringd worden door `<pre>` tags.

**Comment by OlivierSwaak** [comment]
>     * Pro: Kan worden toegevoegd door tussen drie backticks de code te zetten ([Flashcards met code-editor #52 (comment)](https://github.com/NatuurkundePracticumAmsterdam/ecpc/issues/52#issuecomment-2286642458)) of door de code tussen `<pre><code>` te zetten ([Flashcards met code-editor #52 (comment)](https://github.com/NatuurkundePracticumAmsterdam/ecpc/issues/52#issuecomment-2286645598)) (misschien is alleen '`<code>`' al genoeg).

![image](https://github.com/user-attachments/assets/b1bd017b-5aae-488f-bfd8-e5101480dcdb)
Alleen `<code>` werkt ook

**Comment by OlivierSwaak** [comment]
Ik denk dat als deze keuze gemaakt is en dit overeenstemt met de originele bedoeling, het developen van het framework dan klaar is. Vervolgens kan dan als mini-project de flashcards voor elk hoofdstuk worden bedacht, developed en geïmplementeerd (waaronder de juiste CSS grootte gekozen voor de elementen om de whitespace onder te verminderen, dit zal voor elk hoofdstuk anders zijn).

**Comment by OlivierSwaak** [comment]
Ik ben momenteel bezig met het overzetten van de Moodle server (https://github.com/NatuurkundePracticumAmsterdam/ecpc/issues/52#issuecomment-2275769132) naar mijn laptop, alleen ik kon niet meer vinden hoe ik embedding had toegestaan, dus ik zal de bijbehorende forum link hier nogmaals voor de zekerheid posten: https://moodle.org/mod/forum/discuss.php?d=235496.

**Comment by OlivierSwaak** [comment]
Het lukt me ook niet helemaal om de embed knop te displayen nu ik het op mijn laptop probeer over te zetten, ik zal hier later naar kijken hoe we dat kunnen oplossen
![afbeelding](https://github.com/user-attachments/assets/e1447cc5-9faa-46f6-91b8-a3d32cf8f08a)

**Comment by OlivierSwaak** [comment]
Het is een beetje inconsistent of de embed knop wel of niet er komt, dus ik stop nu met proberen het werkend te krijgen. Het werkt op mijn pc, dus ik weet dat het mogelijk is, maar zoals je in de foto kan zien kan het ook een beetje bugged zijn, dus we gaan dit moeten oplossen wanneer we daadwerkelijk de h5p uploaden.
![afbeelding](https://github.com/user-attachments/assets/340ae401-865d-4633-85d1-477c302d05ec)

**Comment by AnneliesVlaar** [comment]
code highligten in flashcard kan niet (makkelijk) via de standaard H5P elementen.

We gaan proberen een eigen element te maken zie https://h5p.org/documentation ([Developer guide](https://h5p.org/developers))

**Comment by OlivierSwaak** [comment]
Hele kleine update, ik heb een van de tutorials proberen te volgen (https://h5p.org/tutorial-greeting-card) alleen het lukt me nog niet om het gemaakte element daadwerkelijk te displayen. Verder helpt het niet dat de cli guide (https://h5p.org/h5p-cli-guide) een beetje outdated is. Ik zal het later nogmaals proberen.

Wel heb ik gevonden dat het kopieren van een codeblock van een webpagina in het invulboxje leidt tot een 'code snippet' (zoals hieronder),
![image](https://github.com/user-attachments/assets/3a7f0134-b7dd-42d5-ad7f-07ade1e2f9a7)
alleen laat h5p dialogcards niet toe dat er een pre tag wordt gebruikt
![image](https://github.com/user-attachments/assets/5d836b7b-e9ad-4da0-9f92-0105fe5e677b)
waardoor het na het renderen alleen code om zich heen heeft
![image](https://github.com/user-attachments/assets/f816eb7f-7bf5-47ad-9043-38d45eee2ba7)
dus ik hoop door hier pre aan de lijst toe te voegen en dit als geedite library te importeren dit te kunnen fixen
![image](https://github.com/user-attachments/assets/5ee09980-fff6-4cf8-b24f-215c5b1c8b9a)

**Comment by OlivierSwaak** [comment]
Ik wilde origineel netjes een fork maken van deze dialogcards library, maar het lukte me niet helemaal om dat werkend te krijgen. Uiteindelijk heb ik gewoon in de al bestaande library de tags aangepast en eindelijk...
![image](https://github.com/user-attachments/assets/b20772a6-f146-4dc5-8c05-557f92359449)
is het gelukt om codeblocks in dialogcards te krijgen!
Ik zal later kijken naar hoe we de syntaxhighlighter erin krijgen, maar ik ben blij dat de codeblocks nu daadwerkelijk werken en geen extra manual labour vereisen. Dit betekent dat we een eerste versie hebben van onze code dialogcards!

**Comment by OlivierSwaak** [comment]
![image](https://github.com/user-attachments/assets/4600dbae-c0e9-4a64-8a9c-a5f2fd097881)
Het werkt ook wanneer ik het embed!
Ik hoef dus niets manually verder toe te voegen.
Volgende keer zal ik kijken of we misschien dus daadwerkelijk highlighting toe kunnen voegen met de codehighlighter in het kaartje en of we de class van de codehighlighter zo kunnen aanpassen dat de kleuren overeenkomen met de mkdocs highlighting!
Ik denk wel dat we nu daadwerkelijk inhoud kunnen gaan developen, aangezien dit dus al een werkend prototype is.

**Comment by OlivierSwaak** [comment]
![image](https://github.com/user-attachments/assets/bf440133-842d-4797-948a-cb318ce288c1)
Ik heb iig gevonden waar ik de kleuren kan aanpassen voor de code highlighting, alleen moet ik dit nu nog ziet te uploaden naar de LMS om te hosten wat een klein beetje moeilijker is dan gedacht:
![image](https://github.com/user-attachments/assets/88bb65fd-3c6c-4f7c-95f0-cc22b9dceba6)
Maar als dat duidelijk is zal het heel makkelijk moeten zijn om alles aan te passen!

**Comment by OlivierSwaak** [comment]
![Image](https://github.com/user-attachments/assets/441c595f-e823-44e8-9d11-64c403309f6d)
Het is me gelukt om de code highlighting te laten werken met de nieuwe mkdocs kleuren.
Het lukte me helaas alleen om dit in Lumi werkende te krijgen dus ik weet nog niet of dit ook gaat werken als we het naar de h5p server uploaden, omdat mijn local LMS hem niet accepteerde.
Er zijn wel helaas 2 problemen:
1. De kleuren zien er door de achtergrond en het lettertype niet heel duidelijk uit.
2. Import statements worden niet volledig gehighlight door de onderliggende highlight code die er onder zit.

**Comment by OlivierSwaak** [comment]
Ik heb de font-family in de css van de code highlighter aangepast naar 'inherit'.
Hierdoor is het basisfont van Lumi geselecteerd en ziet het er al een stuk beter uit.
![Image](https://github.com/user-attachments/assets/6eed11fa-39ef-486e-ae82-5f557d677eef)
Waarschijnlijk betekent dit helaas niet dat roboto automatisch wordt geselecteerd wanneer we de h5p embedden in de handleiding, aangezien (zover ik weet) de font van buiten de embed niet wordt geinherit.

Als we willen zal ik kijken hoe we roboto als standaard font kunnen gebruiken zodat het meer lijkt op de codeblocks in de handleiding.

Ik weet verder niet welk font wordt gebruikt voor de codeblocks van de dialogcards, dus dit kan weer een mismatch opleveren.

**Comment by OlivierSwaak** [comment]
[libraries.zip](https://github.com/user-attachments/files/17534743/libraries.zip)
Dit is verder de huidige versie van de codehighlighter die ik naar Lumi kon uploaden met dus de nieuwe kleuren.

**Comment by AnneliesVlaar** [comment]
Vanwege teveel omwegen en mogelijk weinig rendement. Studenten zullen dit mogelijk niet veel gaan gebruiken, toch besloten het niet verder te gaan ontwikkelen
