### ISSUE TITLE
Mappenstructuur met icoontjes in handleiding toepassen

### ISSUE THREAD

**Issue by AnneliesVlaar** [NatuurkundePracticumAmsterdam/ecpc#57]
Overal in de handleiding waar de mappenstructuur wordt weergegeven deze opbouwen met icoontjes. Ook opletten of er nieuwe mappen/bestanden bijkomen, deze dan met groen (new) weergeven.

**Comment by aminrs02** [comment]
@AnneliesVlaar Ik vraag me af waar de mappenstructuren moeten staan, in de opdracht zelf of daaronder. Ook vraag ik me ook af wat de bedoeling is qua frequentie (echt overal waar ik het me kan bedenken of met net wat meer mate)?

**Comment by AnneliesVlaar** [comment]
Goeie vraag, op het moment dat er in de opdracht gevraagd wordt om een map en/of bestand aan te maken, dan is het fijn als daar een folder structuur naast staat. Om dat mooi uit te lijnen heb ik een class gemaakt "grid-tree" gemaakt (zie docs>assets>folder_tree>folder_tree.css) die met een verhouding 3:1 de opdracht en de tree in kollomen zet. De opdracht en de tree moeten daarbij elk in een aparte div gezet worden. Om dat snel te kunnen neerzetten heb ik een snippet aangemaakt met de naam tree ((zie docs>assets>folder_tree>tree_markdown_snippet.json). Hoe je deze snippet in VSCode kan gebruiken staat ook in https://github.com/NatuurkundePracticumAmsterdam/ecpc/issues/38 . Ik heb de opdrachten in communicatie.md aangepast dan kan je zien hoe het eruit komt te zien.

**Comment by AnneliesVlaar** [comment]
Ik heb ook de laatste versie van dev in de branch 57-... gezet, dan zijn de meeste opdrachten alvast in de nieuwe structuur. Scheelt straks weer voor het mergen.

**Comment by AnneliesVlaar** [comment]
Bij het maken van de folder tree is het belangrijk dat na elke tak er twee spaties staan, anders staat de boom niet goed.

**Comment by AnneliesVlaar** [comment]
Dan nog de frequentie, wat mij betreft liever een keer te vaak dan te weinig. Zodra er in de tekst of opdracht gesproken wordt over een map of bestand, dan daar een folder tree onder of naast. Als je bij een gedeelte specifiek twijfelt of je het er echt 3 keer neer moet zetten, zet dan het voorbeeld hier neer. Dan denken we er even samen over na.

**Comment by AnneliesVlaar** [comment]
@aminrs02 Ik heb de branch 57-mappenstructuur... aangevuld met nieuwe structuur opdrachten. Vaak bij het maken van de nieuwe structuur moest er ook een mappenstructuur bij, dus her en der is dat alvast gedaan. (vergeet niet te Fetchen als je verder werkt ;-) )

**Comment by AnneliesVlaar** [comment]
@aminrs02 Ik heb de branch weer aangevuld met nieuwe structuur opdrachten in CLI en GUI. Hier en daar heb ik ook een lightbulb toegevoegd (voor #54) moeten maar even zien of die nu op een handige plek in de tekst staan.

**Comment by aminrs02** [comment]
@AnneliesVlaar Bedankt! Nog een kleine vraag, op sommige plekken wordt een {{L}} voor de {{folder}} ECPC gedaan en op andere plekken niet, welke heb je liever? Ook heb ik Pythondaq: repository een beetje herschreven en vraag ik bij pythondaq: start script om basisscript.py eerst aan te maken (met directory structure uiteraard) omdat ik dat nog nergens zag.

**Comment by aminrs02** [comment]
En in welke repository past water_rocket.py het beste?

**Comment by aminrs02** [comment]
Er is ook wisselend gebruik van ` ` bij folder namen (wel consistent bij file namen)

**Comment by AnneliesVlaar** [comment]
> @AnneliesVlaar Bedankt! Nog een kleine vraag, op sommige plekken wordt een {{L}} voor de {{folder}} ECPC gedaan en op andere plekken niet, welke heb je liever?

Laten we op alle plekken zonder {{L}} doen.

**Comment by AnneliesVlaar** [comment]
> Ook heb ik Pythondaq: repository een beetje herschreven en vraag ik bij pythondaq: start script om basisscript.py eerst aan te maken (met directory structure uiteraard) omdat ik dat nog nergens zag.

Dat goed. In die folderstructuur is het handig om ook de repository {{github}} oefenopdrachten te zettten zodat het zichtbaar is dat de repository {{github}}pythondaq naast oefenopdrachten moet komen staan.

**Comment by AnneliesVlaar** [comment]
> En in welke repository past water_rocket.py het beste?

Ik zou zeggen in een eigen repository omdat het een opzich zelf staande project is. Dus de repository ... 'projectile-motion' of 'projectile-motion-calculator' oid.

**Comment by AnneliesVlaar** [comment]
> Er is ook wisselend gebruik van `naam` bij de namen in de mappenstructuur (bij poetry wel op sommige andere plekken niet)

Kan je hier meer over vertellen?

**Comment by aminrs02** [comment]
In sommige gevallen wordt de mappenstructuur als volgt weergegeven:

```            
            <div>
            {{github}}`pythondaq`  
            {{T}}{{folder}}`src`  
            {{tab}}{{L}}{{folder}}`pythondaq`  
            {{tab}}{{tab}}{{T}}{{file}}`__init__.py`  
            {{tab}}{{tab}}{{T}}{{file}}`arduino_device.py`  
            {{tab}}{{tab}}{{T}}{{file}}`diode_experiment.py`  
            {{tab}}{{tab}}{{L}}{{file}}`view.py`  
            {{T}}{{new_folder}}`tests`  
            {{tab}}{{T}}{{new_file}}`__init__.py`  
            {{tab}}{{L}}{{new_file}}`test_imports.py`  
            {{T}}{{file_lines}}`pyproject.toml`  
            {{L}}{{file_lines}}`README.md`  
            </div>
```
met "`" en op andere plekken zo:
```
            <div>
            {{folder}} ECPC  
            {{T}} {{github}} Pythondaq  
            {{tab}} {{T}} {{new_file}} basisscript.py  
            {{tab}} {{L}} {{dots}}  
            {{L}} {{dots}} 
            </div>
```
zonder "`". In de tekst wordt consistent gebruik gemaakt van de code blokken bij bestandsnamen, maar in de directory structuur is dat nog wisselvallend zoals hierboven.  Het lijkt me net om daar ook een consistente keuze in te maken.

**Comment by AnneliesVlaar** [comment]
Dat is inderdaad inconsistent, laten we zoveel mogelijk met backticks "`" weergeven. Goed dat je het opmerkt!

**Comment by AnneliesVlaar** [comment]
@aminrs02 Ik heb de laatste wijzigingen weer in de branch 57 gemerged #fetch
