### ISSUE TITLE
cheatsheet title weghalen

### ISSUE THREAD

**Issue by AnneliesVlaar** [NatuurkundePracticumAmsterdam/ecpc#72]

**Comment by AnneliesVlaar** [comment]
kleuren aanpassen, elke onderwep andere kleur

**Comment by OlivierSwaak** [comment]
Het is gelukt om de title weg te halen
![image](https://github.com/user-attachments/assets/1b936876-f91f-4505-b580-48323080fae3)

**Comment by OlivierSwaak** [comment]
Merge succesvol
