### ISSUE TITLE
Fix colour body comparison

### ISSUE THREAD

**Issue by OlivierSwaak** [NatuurkundePracticumAmsterdam/ecpc#73]
De geel-oranje vergelijking werkt alleen maar een kant op (dus als op de body wordt gehoverd zijn beide kanten geel), dus ik zal dit later nog aanpassen.

_Originally posted by @OlivierSwaak in https://github.com/NatuurkundePracticumAmsterdam/ecpc/issues/58#issuecomment-2381345529_

**Comment by AnneliesVlaar** [comment]
Fixed by f134bdfeaef68d2b4f0defe6047d40c4771b9232
